### ISSUE TITLE
Return union type without type annotating `match`

### ISSUE THREAD

**Issue by thought2** [gvergnaud/ts-pattern#10]
The following compiles:

```ts
import { match } from "ts-pattern";

type T = string | number;

const x = match<boolean, T>(true)
  .with(true, () => "")
  .with(false, () => 0)
  .run();
```

Would it be possible to construct a union type along the way in the builder? I mean, so that the above code would compile without the type annotations?

I'm not sure if that's wanted in every scenario, so maybe it would need a second version of `match` for it. In any way, if possible, I'd say this would be a valuable thing to have.

**Comment by gvergnaud** [comment]
Hey!

I kind of think that being explicit about your output is better in this case, even though you need to manually write the union type you expect as output. It might be a bit more verbose but there is a case to be made that it's less error prone and more readable.

I'll leave this issue open and I might reconsider if I see that more people want this

**Comment by thought2** [comment]
My first thought was, that the builtin "pattern match" does create unions, too. Without complains.
```ts
const f = (x: boolean): number | string => {
  switch (x) {
    case true:
      return 1;
    case false:
      return "";
  }
};
```

However, if I look at e.g. the `fold`'s from the `fp-ts` package, which I guess many people will use together with this library. The do behave exactly like the `ts-pattern`'s `match`:

```ts
import * as B from "fp-ts/boolean";

const f = (x: boolean) =>
  B.fold<number | string>(
    () => 1,
    () => ""
  )(x);
```
The type annotation is needed to make this compile. So finally I think it makes sense if this library behaves the same.

In the case of `match` the burden is that, if you supply type hints, you have to do that for the the value, that's matched on, too. But looking at TS's roadmap, they have a topic ["Investigate partial type argument inference"](https://github.com/microsoft/TypeScript-wiki/blob/master/Roadmap.md#future). So this may look like `match<?, string | number>(...)` in the future.

For now I defined
```ts
const match_ = <B>() => <A>(value: A): Match<A, B> => match<A, B>(value);
```

which makes things like `match<string | number>()(...).with(...)` possible. Don't know if it;s the best way to do it, but it works well.

**Comment by m-rutter** [comment]
Yes, its a little tedious having to annotate the generic parameters when your return type is going to be union of some sort. Its esp annoying because you have to provide an input type, which often times doesn't have an type alias and you either have to create a new type alias or do an inline  
```ts
match<typeof value["some"]["prop"]["I"]["match]["on"], ReactNode>(value.prop.I.match.on)`
```

Maybe make the return type the first generic argument rather than the second, given you are much more likely to want to set that over the input type?

```
match<ReactNode>(value.prop.I.match.on)`
```

**Comment by m-rutter** [comment]
Only downside is I suppose this amounts to a breaking change, but even if you were to implement better return type inference I think users will want to specify the return type as a generic argument quite often. Having the return type be the first type parameter might have better overall ergonomics.

**Comment by thought2** [comment]
That's what my wrapper `match_` does above. If you want the first type arg to be provided and the second to be derived you have to put that extra `() =>` between.
https://github.com/Microsoft/TypeScript/pull/26349 will make this maybe easier in future versions of typescript.

**Comment by gvergnaud** [comment]
FWI there is a simpler workaround for this, you can simply annotate the return type of your first handler function, and ts-pattern will infer that as your output type for your other branches as well:

```ts
match(value.some.prop.I.match.on)
  .with({...}, (): ReactNode => (...some react node))
  .with({...}, () => { ... all other branches will expect ReactNode as a return type })
  .run()
```

I looked into implementing a better inference heuristic to output the union of all branches return type when the Output type isn't given explicitly, but it turns out it's pretty complicated, and I'd rather be focusing on adding the remaining features on the roadmap that I think are most important before tackling this

**Comment by thought2** [comment]
cool!

**Comment by m-rutter** [comment]
Ah, yes that workaround works pretty. Its a little intuitive, but its definitely easier than having to specify the input type.

**Comment by gvergnaud** [comment]
👋 I started working on this again, I opened this PR https://github.com/gvergnaud/ts-pattern/pull/23 to infer the ouput type as the union of the types of all branches.

**Comment by m-rutter** [comment]
I'll give it a go

**Comment by m-rutter** [comment]
Seems to work great! I can still restrict the return type by explicitly setting the generic params, but will otherwise correctly infer the union type.

**Comment by gvergnaud** [comment]
Great! I'll probably release this tomorrow then

**Comment by gvergnaud** [comment]
v3.1.1 has been released! I'm closing this issue
