### ISSUE TITLE
Pattern matching on array length

### ISSUE THREAD

**Issue by ghost** [gvergnaud/ts-pattern#105]
_

**Comment by gvergnaud** [comment]
Hi

That's a good feature request, I was thinking about adding a `P.rest(subpattern?)` pattern that could be combine with tuple in patterns that would look like `[1, 2, P.rest(P.number)]` (which would match the type `[1, 2, ...number[]]`) to cover this use case. Would that work for you?

**Comment by tam-carre** [comment]
Duh, that seems like the simplest change, with all the benefits. Sounds good.

Since I like listing out the different usages:

```ts
const nums: number[] = [1, 2, 3, 4, 5, 6]

match(nums)
  // Already implemented
  .with([], (emptyArr) => "type of emptyArr is `[]`")
  .with([P.number], (arr) => "type of arr is `[number]`")
  .with([P.number, P.number], (arr) => "type of arr is [number, number]")

  // New syntax
  .with([P.number, P.rest], (arr) => "type of arr is `[number, ...number[]]`")
  .with([P.number, P.number, P.rest]), (arr) => "type of arr is `[number, number, ...number[]]`")
  .exhaustive()

// Combined with JS destructuring
match(nums)
  // Already implemented
  .with([P.number], ([a]) => "type of a is `number` as opposed to `number | undefined`")
  .with([P.number, P.number], ([a, b]) => "a and b are both of type number as opposed to `number | undefined`")

  // Nwe syntax
  .with([P.number, P.rest], ([x, ...xs]) => "type of x is `number`, type of xs is `number[]`")
  .with([P.number, P.number, P.rest], ([a, b, rest]) => "a and b are `number`, rest is number[]")
  .exhaustive()
```

**Comment by tam-carre** [comment]
Just realised my examples are a little off the mark with `P.rest` usage! I'll update!

**Comment by gvergnaud** [comment]
I gave this a little more thoughts and I'm leaning toward an API that would look like this instead:


```ts
const xs: unknown[] = [1, 2, 3, 'a', 'b', 'c'];

match(xs)
  .with([P.any, ...P.array()], (xs) => [])             // xs: [unknown, ...unknown[]]
  .with([...P.array(), 7], (xs) => [])                 // xs: [...unknown[], number]
  .with([42, ...P.array(P.number)], (xs) => [])        // xs: [42, ...number[]]
  .with([42, ...P.array(P.number), '!'], (xs) => [])   // xs: [42, ...number[], '!']
  .with([1, 2, ...P.array(P.number)], (xs) => [])      // xs: [1, 2, ...number[]]
  .with([...P.array(P.string), 'a', 'b'], (xs) => [])  // xs: [...string[], 'a', 'b']
  .otherwise(() => [])
```


This way we can cover all the features of Variadic Tuple types, like leading spread `[...type1[], type2]` , middle spread `[type1, ...type2[], type3]`.

**Comment by tam-carre** [comment]
Great! I think this will be a very exciting development in the TypeScript ecosystem.

**Comment by gvergnaud** [comment]
I started implementing this, here is the WIP PR 👉 https://github.com/gvergnaud/ts-pattern/pull/114

**Comment by philihp** [comment]
Wow, can't wait to use this!

**Comment by gvergnaud** [comment]
This is going to be part of TS-Pattern v5 (draft pr: #139)

**Comment by gvergnaud** [comment]
Added in https://github.com/gvergnaud/ts-pattern/releases/tag/v5.0.0!
