### ISSUE TITLE
Compile-time performance optimization

### ISSUE THREAD

**Issue by XiNiHa** [gvergnaud/ts-pattern#106]
**Is your feature request related to a problem? Please describe.**
I've been enjoying this library a lot! However, after looking at the source, I'm a bit worried about the overall performance, since it looks much more expensive than usual conditional checks.

**Describe the solution you'd like**
Introduce some kind of compilation step (Babel/SWC plugins? or even standalone) to optimize out the API calls.

**Describe alternatives you've considered**
Not sure. Maybe waiting until JS engines natively support pattern matching and JIT for it? :P

**Comment by gvergnaud** [comment]
Hey, thanks for the suggestion.

pattern matching with ts-pattern will always be more expensive than native support, that's true, but I'm profiling ts-pattern to make it as fast as possible while keeping it as a runtime-only library. I prefer not to turn this project into a compiler because it makes it easier to install in use in any environment

**Comment by BaeoMaltinsky** [comment]
I know this issue is closed, but I'm asking out of curiosity: do you have benchmarks that quantify the difference between `ts-pattern`  and hand-written control flow with respect to performance?

**Comment by bdbaraban** [comment]
I was also curious to compare performance of ts-pattern to built-in conditionals, and have spun up some simple benchmarks. I wrote a discussion post [here](https://github.com/gvergnaud/ts-pattern/discussions/173), but tl;dr; I'm finding that match statements execute ~100% more slowly than built-in control flows.

https://github.com/bdbaraban/ts-pattern-benchmark

**Comment by LukeDefeo** [comment]
@bdbaraban looking at your benchmark it seems to be over 1000 times slower than if/else
1 313 796 ops/s vs 
1 039 743 389 ops/s

Seems like a pretty huge hit and I don't think many apps can justify this

@gvergnaud How much overhead do your internal benchmarks show?
