### ISSUE TITLE
Idiomatic support for dealing with missing properties

### ISSUE THREAD

**Issue by lorefnon** [gvergnaud/ts-pattern#109]
Hello, thanks a lot for creating this library. This has been very useful. 

**Is your feature request related to a problem? Please describe.**
I discovered today that when using ts-pattern we have to careful about missing properties vs properties with undefined values. 

```ts
> match({}).with({ x: P.nullish }, () => 'A').otherwise(() => 'B')
'B'
> match({}).with({ x: P.undefined }, () => 'A').otherwise(() => 'B')
'B'
> match({ x: undefined }).with({ x: P.nullish }, () => 'A').otherwise(() => 'B')
'A'
```

This is inline with how ts also behaves so I am not complaining but for many users this may be unexpected and it would be nice to have an idiomatic solution.

**Describe the solution you'd like**

It would be nice if P.nullish could also detect misssing properties, even if P.null and P.undefined doesn't. 

**Describe alternatives you've considered**
We can clone the source object to have undefined defaults but this gets cumbersome for nested objects etc.

**Additional context**
N/A

**Comment by darrylnoakes** [comment]
What about `P.optional(P.nullish)`?

**Comment by lorefnon** [comment]
Ah ok, missed that. Thanks a lot.

**Comment by thewilkybarkid** [comment]
@lorefnon Could you reopen this? I've had trouble with it too; @darrylnoakes's suggestion works, but I don't want `null` as a possibility, only `undefined` or not set.

`P.optional(undefined)` doesn't work as it wants a `Pattern` rather than a literal. Should `P.optional` be able to take literals?

**Comment by darrylnoakes** [comment]
> I don't want null as a possibility, only undefined or not set.
> P.optional(undefined) doesn't work as it wants a Pattern rather than a literal.

What about `P.undefined`?

**Comment by thewilkybarkid** [comment]
Is there a `P.undefined`? I can't see it.

**Comment by darrylnoakes** [comment]
Sorry, for some reason I thought there was and didn't bother to check.
Yeah, `P.optional` being able to take a literal seems to be a good solution, and would probably be useful in other cases too.
Or is there a specific reason that it only takes a `Pattern` currently, @gvergnaud?

**Comment by darrylnoakes** [comment]
Looking at the source and experimenting, `P.optional` _does_ allow literals, but `undefined` gives the error "argument of type `undefined` is not assignable to parameter of type `Pattern<string>`." It seems that the input type has been narrowed to string, preventing passing `undefined` or `null` as a literal.

**Comment by thewilkybarkid** [comment]
Seems that in v5 `P.optional(undefined)` now works. 🎉

**Comment by jb-asi** [comment]
Do we see any issue with the first match here, or no? The original example followed up with `.otherwise`; but `exhaustive` will throw an error:

``` bash
Error: Pattern matching error: no pattern matches value {}
```

``` ts
type Obj = {
  prop?: undefined;
};

const obj: Obj = {
  // prop is not included
} as const;

// first match
// will throw but does not emit a type error
match(obj)
  .with({ prop: undefined }, () => {})
  .exhaustive(); 

// second match
// works thanks to @thewilkybarkid (but one cannot rely on type errors)
match(obj)
  .with({ prop: P.optional(undefined) }, () => {})
  .exhaustive(); 
```

Thanks!
