### ISSUE TITLE
Add peerDependency on TypeScript ^4.0.0in ts-pattern ^2.0.0

### ISSUE THREAD

**Issue by EricCrosson** [gvergnaud/ts-pattern#11]
Hi @gvergnaud, 

Is TypeScript ^4.0.0 a requirement to consume ts-pattern ^2.0.0? I found this line on the [v2.0.1 rc](https://github.com/gvergnaud/ts-pattern/releases/tag/v2.0.1-next.2)

> People using earlier versions of TS will need to upgrade in order to use ts-pattern v2+.

It's not clear to me if only ts-pattern needs a TS version 4-or-greater or if consumers of ts-pattern do too. If it's the latter case, we should add a peerDependency in the package.json to codify this to `npm`

**Comment by gvergnaud** [comment]
I'm not sure it's very common practice to list the language itself as a peer dependency. I'm going to add a note to the readme for now
