### ISSUE TITLE
Property 'infer' does not exist on type 

### ISSUE THREAD

**Issue by JusttCallMeMike** [gvergnaud/ts-pattern#116]
**Describe the bug**
```
import { match,P } from 'ts-pattern';
type DateType = string|Date|Dayjs
...
.with([P.infer<DateType>, undefined], ()=>
```
gives me  ```Property 'infer' does not exist on type 'typeof import(\"/Users/zeno/Work/cryptopus/node_modules/.pnpm/ts-pattern@4.0.5/node_modules/ts-pattern/dist/patterns\")'.",```
**Versions**
- TypeScript version: 4.8.4
- ts-pattern version: 4.0.5
- environment: node version v18.10.0

**Comment by gvergnaud** [comment]
Hey,

`P.infer` actually does the opposite of what you're trying to achieve: it takes a type of pattern (e.g `typeof P.number`) and turns it into a regular type (e.g `number`).

If you want your example to work, you would need to do this instead:

```ts
import { match, P } from 'ts-pattern';

const datePattern = P.union(P.string, P.instanceOf(Date));

type DateType = P.infer<typeof datePattern>;

...
.with([datePattern, undefined], () => ...)

```
