### ISSUE TITLE
Wildcard Proposal: P.strictNumber (matches numbers, ignores NaN)

### ISSUE THREAD

**Issue by tylerbarker** [gvergnaud/ts-pattern#119]
**Is your feature request related to a problem? Please describe.**
I have found myself in situations where I would like to match on a number using `P.number`, but having to cater for the case where the `number` value matched is `NaN` feels odd to me. I understand why this happens given that `typeof NaN` is in fact `number`.

**Describe the solution you'd like**
Ideally, I'd love for `P.number` to just ignore `NaN`. That said, I understand there are likely use cases for this not being the case so I'm proposing extending the API with a new match type of `P.strictNumber` (or similar name) which exists to serve the use case of matching only valid numbers and ignoring `NaN`.

**Describe alternatives you've considered**
Currently I am matching on the `NaN` literal in a match above the `P.number` match, but it just duplicates the `otherwise` case.

**Additional context**
I would be happy to try making this contribution myself if you feel it would be a welcome addition.

**Comment by gvergnaud** [comment]
Hey! Thanks for the feature requests I'll think about it.

In the meantime you can define this pattern yourself:

```ts
const strictNumber = P.intersection(P.not(NaN), P.number);
```

**Comment by tylerbarker** [comment]
Oh that's cool, I did not think of that! Quite a nice solution perhaps the extension is unnecessary then 😅 cheers for the response.
