### ISSUE TITLE
.exhaustive() doesn't include undefined case

### ISSUE THREAD

**Issue by brianalexander** [gvergnaud/ts-pattern#124]
**Describe the bug**
`undefined` match not being highlighted when using `.exhaustive()`

```javascript
import { match, P } from "ts-pattern";
match<undefined | "1">(undefined)
  .with(P.not(P.nullish), (thing) => thing)
  .exhaustive(); // this is an error, but no hinting from exhaustive
```

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/headless-resonance-ojmso0

**Versions**
- TypeScript version: 4.9.3
- ts-pattern version: 4.0.6
- environment: node 16.14.2

**Comment by gvergnaud** [comment]
Thank you for the report, I'll take a look soon

**Comment by gvergnaud** [comment]
Looks like this is no longer happening, but I haven't checked when this was fixed: https://codesandbox.io/s/nice-hawking-t458r6?file=/src/index.ts
