### ISSUE TITLE
Avoiding specifying input parameter for 'match' in Typescript

### ISSUE THREAD

**Issue by dcarapic** [gvergnaud/ts-pattern#126]
It would be nice if I would not need to specify the input parameter for the `match` function and only specify the return parameter.
There are two solutions that I can see:  

1. Specify the output parameter first. This would allow Typescript to infer the input based on the given parameter. This however would be a breaking change so I'm not sure it is possible.
2. Add a variant of `match` which has two chained functions so you could do:
`match({id: "Bla"}).to<number>().with ...`

I realize I can do the variant 2 myself in code but I just thought it would be a nice option.

**Comment by gvergnaud** [comment]
Hey! Great suggestion. I might very well add this in a minor release, I often find myself needing this too. I usually end up doing something like this:

```ts
declare const input: /* Some input */ ;

return match<typeof input, MyOutputType>(input)
  .with(...)
  .otherwise(...)
```

This is ok when your input is assigned to a variable, but it doesn't work when it's not.

**Comment by anikeef** [comment]
I currently ended up using this approach, but removing extra parentheses in function call would be good:

```typescript
/**
 * This is a workaround to avoid specifying first type argument to `match`.
 *
 * @example
 * const input: [number, number] = [1, 2]
 *
 * matchPattern<string>()(input)
 *   .with([1, 2], () => 'one two')
 *   .with([3, 4], () => 'three four')
 */
export const matchPattern = <O>(): typeof match => <I>(i: I) => match<I, O>(i)
```

**Comment by anikeef** [comment]
I ended up with this approach, but removing extra parentheses would be better.

```typescript
/**
 * This is a workaround to avoid specifying first type argument to `match`.
 *
 * @example
 * const input: [number, number] = [1, 2]
 *
 * matchPattern<string>()(input)
 *   .with([1, 2], () => 'one two')
 *   .with([3, 4], () => 'three four')
 */
export const matchPattern = <O>() => <I>(i: I) => match<I, O>(i)
```
