### ISSUE TITLE
Type error for `typescript <= 4.6.4` with `ts-pattern == 4.1.2`

### ISSUE THREAD

**Issue by adamhamlin** [gvergnaud/ts-pattern#134]
**Describe the bug**
For TypeScript projects using the `match` function (v4.1.2) and typescript version <= 4.6.4, there is the following type error:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/18332856/211568524-2a82c98b-3dbb-41fd-9996-b3d1c27bc986.png">

Not that every release should support every version of typescript back to the beginning of time, but this is a breaking change for a relatively recent typescript version (less than a year old). 

**Code Sandbox with a minimal reproduction case**
Probably overkill for this particular situation

**Versions**
- TypeScript version: <= 4.6.4
- ts-pattern version: 4.1.2
- environment: node 14/16/18

**Comment by gvergnaud** [comment]
Thanks, I just published a fix for this. Upgrading toe 4.1.3 should solve this issue

**Comment by adamhamlin** [comment]
Awesome, thank you!
