### ISSUE TITLE
fp-ts E.left and E.right problems with 4.1.3

### ISSUE THREAD

**Issue by thewilkybarkid** [gvergnaud/ts-pattern#137]
**Describe the bug**
Using `E.left()` or `E.right()` in a `with()` no longer works (https://github.com/PREreview/prereview.org/pull/590). The types are `E.Either<E, never>`/`E.Either<never, A>` rather than just `E.Left<E>`/`E.Right<A>`, and it seems to no longer be able to throw away the `never`s.

Testing the structure directly rather than using the fp-ts constructors works (since there's no `never`).

**Code Sandbox with a minimal reproduction case**
[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgU2DAFsqcCGBnOAUTgF84AzKCEOAcnLAFoY9aAoUSWROEHGAMboANHAAKpClRq0WjMPxhYAduzYATZAIA2OKMjgCIyvPABuObQFdkALiIA6QmkxQAPMqsgARllGmoYGUAcwA+NjYAeki4dQhkPFV4AHdoAGs2IxN4JVMARntabWRyGFo4AB86QOD0MrgAXl5+IQAKC2tkAEo2ODgHZJdWwgcautaxBwCg4K7RVq7G0OrgWvr8Q2NTHr6BoZHi0omHTx8sObgFpbpD9YIs7d7+5AAPdBwrU2AzZAWI6LgqSgaTwmS2OQSMAATIVbuUqrQxvUmnxBOh2pYbDt+oMMK0kEj7JNpiFSPNFg1lojVnVyhsHjBsXs8UhbkSTl5fNgSOTrkUSndNtkma93p8YN9fj0gA)

**Versions**
- TypeScript version: 4.9.4
- ts-pattern version: 4.1.3
- environment: Node 18.13.0

**Comment by gvergnaud** [comment]
Hey,

This is expected given the way `E.left` and `E.right` are typed. Both return a `E.Either<_, _>` which isn't precise enough for ts-pattern to perform its exclusion. It would work if `E.left` returned a `E.Left<_>`.

My recommendation is to build your own custom generic pattern with `P.when` and use them instead:

```ts
import { either as E } from 'fp-ts'
import { match, P } from 'ts-pattern'

declare const value: E.Either<number, string>

const leftP = <I, Pat extends P.Pattern<I>>(value: Pat) =>
  P.when((value): value is E.Left<P.infer<Pat>> =>
    Boolean(value && typeof value === 'object' &&  'left' in value)
  )

const rightP = <I, Pat extends P.Pattern<I>>(value: Pat) =>
  P.when((value): value is E.Right<P.infer<Pat>> =>
    Boolean(value && typeof value === 'object' &&  'right' in value)
  )

const test1: 'left' | 'right' = match(value)
  .with(rightP(P.string), (x) => 'right' as const)
  .with(leftP(P.number), (y) => 'left' as const)
  .exhaustive()
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgU2DAFsqcCGBnOAUTgF84AzKCEOAcnLAFoY9aAoUSWROEHGAMboANHAAKpClRq0WjMPxhYAduzYATZAIA2OKMjgCIyvPABuObQFdkALiIA6QmkxQAPMqsgARllGmoYGUAcwA+NjYjE3htZHIYCQBeODcASVExfhQADyVldQIxB0yYJShlNNDQgAoLaztxfgBKOETwuHEHAHdMZWrayxsm+zqbOGACQgcAGTiYNyKg8iwF-irW9o64ACEICFicPtGDADITuBgATzBkCHI4Y9bE5NoIbwArLRhaODOO2li8R+QQeg2QTTYHQhkWMpjggWC6ASrRS6Ua8GQuWQ+UKxUUKkqNWO9hKLTakM6PWx-WOw1B9XGkwcACVgIj5otlMt3CV1uStjs9gcjmDfucrjc7vSxs8Xm9PgJvmL-gikcDlNLwRToVE4UpTABGewAuY-AA+dFVSuSfEE6AG9QhHW6LmqVrE1SKASCwSaomq2TJoUtbLVuAIupgTrgLow1UBCU9Dk8Piwfrg1UuQboCZ++EMsKjFIcmPQOCspmAZmQ1WhQA)

**Comment by thewilkybarkid** [comment]
Hi @gvergnaud,

Thanks for confirming. I like the idea of setting some more formal integration with fp-ts. I'll see if I can work it out, but that example wouldn't work would it if the left or right had a union type (as it doesn't check the value): [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgU2DAFsqcCGBnOAUTgF84AzKCEOAcnLAFoY9aAoUSWROEHGAMboANHAAKpClRq0WjMPxhYAduzYATZAIA2OKMjgCIyvPABuObQFdkALiIA6QmkxQAPMqsgARllG0cWjgAHzpvWgA+NjYjE3htZHIYCQBeODcASVExfhQADyVldQIxBxyYJShlTIiIgAoLaztxfgBKOBSouHEHAHdMZTqGyxtW+0abOGACQgcAGUSYN1LgZXIsZf5ajq7uuAAhCAgEnEGJgwAyC7gYAE8wZAhyOHOOlLTaCG8AKy0YIKu3VoCSSQVWLxGyFabG60JixlMcCgwAA5uhkh10lkWvBkAVkEUSmVFCoavVzvZyu1OjCev0CUNzmMIU0pjMHAAlVHo5YOVbrdzlbY0vYHI4nM6QuCAu4PJ4sybvD5fX4Cf7S650ZFo9Xgpm0uEAekNN3Q0zgeHQECs2nUFBwwG0uHgUCsyhgoAMwGeaFo7K5OrctHCEVE3is8HUEGQeFU8HwpoM2vRCq9BGUEHgQi0AGtkOp4XEbjGYABGezAxZBUK0ZPqtJ8QToYZNaHdPouOp1sR1AK0VqiOp5akRLXc9UJ2KmNtwDsYOog5J1UqeHxYAdwOq3Ed0RdBScImAzhx49A4KymYBmZB1I0mjDm8gO7QEWVaTACHOrFGGaD6NXaLcYYRnAvTWrauBqlYliAaB0A5puqxGFA-4wIB7S5K67qergr6YEi46pmycAZlmH55gWU7wEopgAEwVnuIRjjqQQNvwQgtqMtJzs23a9oEuG-nEG5DjutbjvuBBUcevSdouPYrl4vhQCJ247LuVaCdJ3Gnuel7Xre0RAA).

I'll also see if I can get it to pick out the `right` or `left` value (so like using `P.select()`).

**Comment by gvergnaud** [comment]
Ah yes you're right! I forgot to use `isMatching` in the guard function:

```ts
import { match, P, isMatching } from 'ts-pattern'

const leftP = <I, Pat extends P.Pattern<I>>(pattern: Pat) =>
  P.when((value): value is E.Left<P.infer<Pat>> =>
    Boolean(value && typeof value === 'object' &&  'left' in value) && isMatching(pattern, (value as E.Left<unknown>).left)
  )

const rightP = <I, Pat extends P.Pattern<I>>(pattern: Pat) =>
  P.when((value): value is E.Right<P.infer<Pat>> =>
    Boolean(value && typeof value === 'object' &&  'right' in value) && isMatching(pattern, (value as E.Right<unknown>).right)
  )
```

**Comment by gvergnaud** [comment]
Going to close this issue since a workaround has been provided
