### ISSUE TITLE
.with and Pattern.not error since 4.1.3

### ISSUE THREAD

**Issue by adrienharnay** [gvergnaud/ts-pattern#138]
**Describe the bug**

Since 4.1.3, when using `Pattern.not`, the following branches will act as if `Pattern.not` was in fact `Pattern.any`. If narrowing in following branches cannot be done, then I would expect the contrary (no narrowing on `Pattern.not` usages).

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/typescript-playground-export-forked-48dyon?file=/index.ts

**Versions**
- TypeScript version: 4.9.4
- ts-pattern version: 4.1.3
- environment: Node 18.11.0

Thanks in advance!

**Comment by gvergnaud** [comment]
Thanks definitely a bug, will take look shortly

**Comment by gvergnaud** [comment]
I had a look and it turns out it's incredibly difficult to solve without breaking exhaustive checking for not patterns. It would be much simpler if TypeScript had [Negated Types](https://github.com/microsoft/TypeScript/pull/29317) but it unfortunately doesn't.

In the meantime, the best workaround is to use `P.not` after other cases:

```ts
import { match, Pattern } from "ts-pattern";

type Input = { type: "video"; seconds: number };

let input = ({ type: "user", name: "Gabriel" } as unknown) as Input;

const output = match(input)
  .with({ type: "video", seconds: 10 }, () => "video of 10 seconds.")
  // Swapped these 👆👇
  .with(
    { type: "video", seconds: Pattern.not(10) },
    () => "not video of 10 seconds."
  )
  .otherwise(() => "something else");
```

**Comment by adrienharnay** [comment]
Ah... That's a shame. The replication is a very simple example of my real code, which looks like this:

```
match(object)
.with({ __typename: 'Something', conflicts: Pattern.not([]) }, () => 0)
.with({ __typename: 'Something', updated_at: Pattern.string }, () => 1)
...
```

Any idea how to replace `Pattern.not([])`?

**Comment by gvergnaud** [comment]
Yes, you could use `P.when(xs => xs.length > 0)`

**Comment by adrienharnay** [comment]
Ah yes, of course! Thank you. Maybe it would make sense to update the docs for `Pattern.not` to mention this breaks narrowing in following branches?

**Comment by gvergnaud** [comment]
Hey, I found a way to fix this issue in the end. It's not perfect but it solve your use case, see details in the release note: https://github.com/gvergnaud/ts-pattern/releases/tag/v4.1.4

**Comment by jasikpark** [comment]
thx for fixing this, sucks that negated types can't be used but it's cool to see this library develop -- I hope for the day we get rust-esque exhaustive `match { }` value blocks in TS / JS
