### ISSUE TITLE
Empty arrays, without `when`?

### ISSUE THREAD

**Issue by tvedtorama** [gvergnaud/ts-pattern#14]
This fails by returning `Array of cats`, not `Empty array`.  The logic might make sense, the array is indeed an empty array of cats.  However, it would be useful to test for empty arrays - without receding to `when`.  Is there a way to do that?

```typescript
const isEmptyArray = match({keys: []})
	.with({keys: ["cat"]}, () => "Array of cats")
	.otherwise(() => "Empty array")

isEmptyArray.should.equal("Empty array")
```

**Comment by gvergnaud** [comment]
Hello!
Agreed that this case can be a bit counter intuitive, but empty lists match all types of list patterns. If you want to handle the empty list case, you can do so explicitly:

```ts
const isEmptyArray = match({keys: []})
        .with({keys: []}, () => "Empty array")
	.with({keys: ["cat"]}, () => "Array of cats")
	.otherwise(() => "Empty array")

isEmptyArray.should.equal("Empty array")
```

Sandbox: https://codesandbox.io/s/recursing-butterfly-q6qgy?file=/src/App.tsx

**Comment by tvedtorama** [comment]
Explicit test for empty works perfectly for me.  I assumed something like that would just always be a match, ignoring the more explicit cat case, which is fortunately not what's happening.
