### ISSUE TITLE
Exhaustive does not work when type guard argument is constrained

### ISSUE THREAD

**Issue by richard-ejem** [gvergnaud/ts-pattern#140]
Code below shows it clearly: when a type guard is used in P.when, following `exhaustive` call reports compile-time error only when the type guard does not have input argument type constraint.

**Expected:** both `reportsError` and `doesNotReportError` below report compile-time type error

**Actual:** only `reportsError` below reports  compile-time type error,  `doesNotReportError` does not

```
type FooBar = "foo" | "bar";
const c: FooBar = "foo" as FooBar;

const reportsError = match(c)
  .with(
    P.when((c): c is "bar" => c === "bar"),
    () => "b"
  )
  // @ts-expect-error
  .exhaustive();

const doesNotReportError = match(c)
  .with(
    // DECLARING TYPE GUARD ARGUMENT TYPE IS THE PROBLEM
    P.when((c: FooBar): c is "bar" => c === "bar"),
    () => "b"
  )
  .exhaustive();
```

See https://codesandbox.io/s/competent-andras-043wve to test it live.

**Comment by gvergnaud** [comment]
Thanks for opening this issue, fixed in v4.2: https://codesandbox.io/s/frosty-tree-fcromf?file=/one-file-demo.ts
