### ISSUE TITLE
ts-pattern fails with template strings/literals

### ISSUE THREAD

**Issue by 205g0** [gvergnaud/ts-pattern#141]
**Describe the bug**
Not sure if it's me but pretty much the title.

**Code Sandbox with a minimal reproduction case**
https://stackblitz.com/edit/typescript-v1vx5s?file=index.ts

You need to "open in new window" to run it!

**Versions**
- check Stackblitz

**Comment by gvergnaud** [comment]
Hey, you need to call exhaustive, otherwise or run to get the value out of the match expression: https://stackblitz.com/edit/typescript-e4mhjd?file=index.ts
