### ISSUE TITLE
problem with P.array matcher (Argument of type not assignable to 'Matcher<never, unknown, any, any, unknown>'.)

### ISSUE THREAD

**Issue by cs4inctec** [gvergnaud/ts-pattern#148]
**Describe the bug**
Apparently ts-pattern 4.2 is not compatible with typescript 4.9.5 / 4.8.4.
While upgrading I encountered the following issue:

> Argument of type '{ title: GuardP<unknown, string>; content: GuardP<unknown, string>; }' is not assignable to parameter of type 'Matcher<never, unknown, any, any, unknown>'.
>   Object literal may only specify known properties, and 'title' does not exist in type 'Matcher<never, unknown, any, any, unknown>'.ts(2345)

reproducible with the P.array example from the README.

```ts
type Input = readonly { readonly title: string; readonly content: string }[];

const input: Input = [
  { title: 'Hello world!', content: 'This is a very interesting content' },
  { title: 'Bonjour!', content: 'This is a very interesting content too' },
];

const output = match<Input, string>(input)
  .with(
    P.array({ title: P.string, content: P.string }),
    (posts) => 'a list of posts!',
  )
  .otherwise(() => 'something else');
```

ts-pattern 4.2 + typescript 4.8 also error
ts-pattern 4.1 + typescript 4.9 works
ts-pattern 4.1 + typescript 4.8 works

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/p/sandbox/basic-node-fp-ts-forked-8plx0q?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A16%7D%5D&file=%2Fsrc%2Findex.ts

**Versions**
- TypeScript version: 4.9.5
- ts-pattern version: 4.2.0
- environment: node version 19.6.0

**Comment by gvergnaud** [comment]
Thanks for the report, fixed in v4.2.1
