### ISSUE TITLE
combining branches

### ISSUE THREAD

**Issue by m-rutter** [gvergnaud/ts-pattern#15]
Interesting library. I've been using this library: https://paarthenon.github.io/variant/ So my feedback comes from my experience with using that. One of its nice features is that you can combine branches: https://paarthenon.github.io/variant/docs/use/matching#-matcher

For example:

```ts
type FooBarBaz = {type: "foo"} | {type: "baz"} | {type: "bar"}
declare const foobarbaz: FooBarBaz;

swtich (foobarbaz.type) {
  case "foo":
  case "bar":
    // handle both foo and bar in a single branch
  case "baz: 
    // handle baz in its own branch 
}

// variant:

matcher(foobarbaz)
  .when(["foo", "bar"], (foobar) => {})
  .when({baz: (baz) => {} })
  .complete()
```

**Comment by gvergnaud** [comment]
I'm actually planning on solving that in the near future, I even have a branch implementing a `oneOf(...patterns)` helper: https://github.com/gvergnaud/ts-pattern/tree/add-one-of-pattern

The API would look like this: 

```ts
import { match, oneOf } from 'ts-pattern';

type Input = { type: 'a' } | { type: 'b' } | { type: 'c' };

match<Input>({ type: 'a' } as Input)
  .exhaustive()
  .with(oneOf({ type: 'a' }, { type: 'b' }), (x) => 'a or b')
  .with({ type: 'c' }, () => 'c')
  .run();
```

Would this solve this issue for you?

**Comment by m-rutter** [comment]
Yes, that probably does it. I guess the only thing variant's matcher has over that is it doesn't need additional helper functions. I'll continue to give it a play around and see how things feel.

**Comment by m-rutter** [comment]
If you use the helper function does it still do exhaustiveness checks?

**Comment by gvergnaud** [comment]
> If you use the helper functions does it still do exhaustiveness checks?

yep

**Comment by gvergnaud** [comment]
I opened a PR implementing a way to give several patterns to `.with()` https://github.com/gvergnaud/ts-pattern/pull/18 . In the end I decided against having a `oneOf` helper because it complexifies the inference of the pattern type. 

I published a pre-release (`2.2.1-next.1`), but it will only work for TS >= v4.2. I might make it TS v4 compatible before merging by using function overloads instead of using [middle rest function arguments](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#non-trailing-rests).

Feel free to try it and to give me your feedback

**Comment by m-rutter** [comment]
Looks good. I'll need to upgrade my codebase to 4.2 to try it, but I was planning on doing that this week anyway.

**Comment by gvergnaud** [comment]
I just publish the `2.2.1-next.2` pre-release which uses function overloads instead of middle rest arguments so it should work fine with all version of TS now

**Comment by m-rutter** [comment]
Just gave it a whirl, and it seems to work well. Its a shame that the `oneOf` utility was too complex, because the full pattern can be a little verbose at times, its quite usable in this form as well:

```ts
  return match(blobParts)
    .with(
      { type: "avatar" },
      { type: "brand" },
      { type: "icon" },
      { type: "agent_login" },
      { type: "splash" },
      (blobParts): string | undefined =>
        generateBlobFilePath(blobParts.blobAuthId, blobParts.fileName)
    )
    .otherwise(() => undefined);
```

**Comment by m-rutter** [comment]
Personally I quite like the 4.2 middle rest arguments as a feature, but I can understand your conern that 4.2 is still quite new.

**Comment by m-rutter** [comment]
I have to say I'm quite impressed by the library, and I do hope that it does well. I'm starting to use it in quite a few places. It seems to be growing in stars quite quickly as of late, which is nice.

**Comment by gvergnaud** [comment]
Closing this issue since v2.2.2 has been released
