### ISSUE TITLE
P.when() is unsafe

### ISSUE THREAD

**Issue by kaguya3222** [gvergnaud/ts-pattern#153]
**Describe the bug**
I am new to this beautiful library, so maybe I am missing something 🤔

When using `P.when` function, it seems that it removes `null` and `undefined` for matched data. 

For example:

```
type Data = {
  digit: number;
};

type Input = {
  data: Data | undefined;
};

const input: Input = { data: undefined };

const result = match(input)
  .with(
    {
      data: P.when((data) => {
        return data.digit > 5; // error, data is undefined!
      })
    },
    () => "digit is more than 5"
  )
  .otherwise(() => "digit is less than 5");
```

**Code Sandbox with a minimal reproduction case**
[Here it is](https://codesandbox.io/s/intelligent-neco-evqmsc?file=/src/index.ts)

**Versions**
- TypeScript version: 4.9.5
- ts-pattern version: 4.2.2
- environment: Google Chrome 112.0.5615.121

**Comment by WoLfulus** [comment]
You can cover the edge case like this, but I do agree I was expecting data to be `Data | undefined` in that predicate argument.

```ts
const result = match(input)
  .with({ data: P.nullish }, () => "data is missing")
  .with({ data: { digit: P.when((digit) => digit > 5) } }, () => "digit is more than 5")
  .otherwise(() => "digit is less than 5");  
```

**Comment by gvergnaud** [comment]
Thanks for the report, fixed in the next major version: https://github.com/gvergnaud/ts-pattern/pull/139/commits/6bda6336f0608249be5fff59dcd057ece03614cd

**Comment by gvergnaud** [comment]
Fixed by https://github.com/gvergnaud/ts-pattern/releases/tag/v5.0.0
