### ISSUE TITLE
Shorthand for P.not(P.nullish)

### ISSUE THREAD

**Issue by gkiely** [gvergnaud/ts-pattern#154]
**Is your feature request related to a problem? Please describe.**
Requiring 2 commands to check if something is non-nullish `P.not(P.nullish)`

**Describe the solution you'd like**
A shorthand `P.nonNullish` so developers do not have to use 2 commands `P.not(P.nullish)` and get intellisense when using `P.`

**Comment by JUSTIVE** [comment]
Agree with this idea, but I suggest `P.some` for  `P.nonNullish`, and `P.none` for `P.nullish`(names borrowed from Option<T>).
