### ISSUE TITLE
Updating to 5.0.0 match doesnt work (Expected 0 arguments, but got 1) 

### ISSUE THREAD

**Issue by BrahimMasmoudi** [gvergnaud/ts-pattern#169]
hello,
I'm using nuxtJs 2 with typescript and firebase functions.
I'm updating ts-pattern in firebase functions :   "ts-pattern": "5.0.0" 
when i use match(input).with().with().otherwise(), (import { match } from 'ts-pattern')
i got this error while calling match : TS2554: Expected 0 arguments, but got 1. it doenst accept input as a param.

also in match.d.ts it's not compiling :  
<img width="836" alt="image" src="https://github.com/gvergnaud/ts-pattern/assets/16254399/13d04d83-3592-45b0-aac5-ba0b3123fbb3">

<img width="421" alt="image" src="https://github.com/gvergnaud/ts-pattern/assets/16254399/0c28cd2f-40b5-4a9e-ae22-f29a83fce816">

is there a solution please ?
thank you

**Versions**
- TypeScript version: 5.1.6
- ts-pattern version: 5.0.0
- environment: chrome / nuxtjs 2

**Comment by gvergnaud** [comment]
Looks like your version of TypeScript does not support const type parameters, so I doubt it really is 5.1.6. If you can repro in a TS playground with this version of TS, please share a link here!

**Comment by BrahimMasmoudi** [comment]
hello, thank you for your response.
indeed, the typescript version used in the editor was set on bundled (4.8.4).
thx again !
