### ISSUE TITLE
can't filter nullish type after checking nullish in match

### ISSUE THREAD

**Issue by dante01yoon** [gvergnaud/ts-pattern#185]
**Describe the bug**

```ts
import {  P, match } from "ts-pattern";


interface ErrorBoundaryProps {
  children: ReactNode
  fallback?: (error: Error) => ReactNode | ReactNode
}

interface ErrorBoundayState {
  hasError: boolean
  error: Error | null
}
// ...
  match(this.props.fallback)
      .with(P.nullish, () => null)
      .with(P.instanceOf(Function), () => this.props.fallback(this.state.error)) // <- shouldn't complian because P.nullish already checked it's not null or undefined
     

```

![스크린샷 2023-07-24 오후 5 14 46](https://github.com/gvergnaud/ts-pattern/assets/6510430/b300bff1-8957-4d71-beaa-d20f6de1b6f3)

Hi! 
I think  second `with`  shouldn't complain  type error.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/<your-sandbox-id>

**Versions**
- TypeScript version: ^5.0.2
- ts-pattern version: ^5.0.4
- environment: chrome, vite

**Comment by gvergnaud** [comment]
👋 I think you should do that instead:

```ts
return match(this.props.fallback)
    .with(P.nullish, () => null)
    .with(P.instanceOf(Function), (fallback) => fallback(this.state.error));
    //                                                     👆 parameter
```

 TS-Pattern doesn't narrow the type of contextual values, like `this.props.callback`, but provides a narrowed version of the value you are matching on as a parameter to your handler.

**Comment by dante01yoon** [comment]
> 

@gvergnaud  Oh, I see! I forgot to get reference from call back parameter. It make sense. thank you!
