### ISSUE TITLE
Nullish pattern doesn't work with omitted fields

### ISSUE THREAD

**Issue by IonasNeonakis** [gvergnaud/ts-pattern#201]
**Describe the bug**
Pattern matching with nullish wildcard doesn't work as expected when field is omitted in the object

**Code Sandbox with a minimal reproduction case**
```import { isMatching, P } from "ts-pattern";

const pattern = {
  field: P.nullish
};

interface MyType {
  field?: string;
}
const notMatching: MyType = {};

console.log(isMatching(pattern, notMatching)); // should return true, returns false
```

https://codesandbox.io/s/typescript-playground-export-forked-lqc4cr?file=/index.ts

**Simple test**
Here is a simple test that fails 
```
  it('should match nullish wildcard when key is missing from object', () => {
    const pattern = {
      field: P.nullish
    };

    const something: unknown = {};

    const isMyType = isMatching(pattern);
    expect(isMyType(something)).toBe(true);
  });
```

**Versions**
- TypeScript version: 5.2.2
- ts-pattern version: 5.0.5
- environment: Node v20.5.1

**Comment by IonasNeonakis** [comment]
A workaround would be to replace 
```
    const pattern = {
      field: P.nullish
    };
    
```
    with 
    
        ```
const pattern = {
      field: P.nullish.optional()
    };
```

**Comment by gvergnaud** [comment]
@IonasNeonakis this actually is the expected behavior. Just like with typescript types, the key must be present on the input object if it is defined on the pattern, unless you use the `.optional()` modifier, or you wrap your pattern into `P.optional(pattern)`. Closing the issue
