### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by acd02** [gvergnaud/ts-pattern#21]
Hello,
first, nice work on the lib 👍 

Okay, so I've noticed a little mismatch in your README (inside the `select` patterns section):
```ts
const output = match<Input>(input)
    .with(
      { type: 'post', user: { name: select('username') } },
      (_, { username }) => username // username: string 👈, it should be ({ username}, _ ) => username
    )
    .otherwise(() => 'anonymous');
```

And also, the `select` codesandbox example leads to a codesandbox where no use of `select` is made ^^

**Comment by gvergnaud** [comment]
Thanks for letting me know! Just fixed those two issues
