### ISSUE TITLE
Enter multiple pipeline for objects type match

### ISSUE THREAD

**Issue by dante01yoon** [gvergnaud/ts-pattern#223]
**Is your feature request related to a problem? Please describe.**

Would be good enter multiple type match 
```ts
const abTest = {
  "A":  true,
  "B": true,
  "C": false,
};

match(abTest)
  .with(P.select({ A: true }), () => ...)
  .with(P.select({ B: true}), () => ...)
  .with(P._ ,() => ...)
  .exhaustive() 
// A
```

current match .. exhaustive only goes in single pattern matching callback, would be better use multiple conditions' callbacks 

**Describe the solution you'd like**
Like
```ts
match(abTest)
  .with(P.select({ A: true }), () => { console.log("A")})
  .with(P.select({ B: true }), () => { console.log("B")})
  .with(P._ ,() => { console.log("C")} )
  .asMultiple()
  .exhaustive()
// A
// B
```
**Describe alternatives you've considered**

**Additional context**

**Comment by gvergnaud** [comment]
You should use several ifs and `isMatching` for that:

```ts
if (isMatching({ A: true })) console.log("A")

if (isMatching({ B: true })) console.log("B")
```

a `match` expression evaluate to a single return value, so we can't evaluate multiple branches otherwise it would have to return multiple values.
