### ISSUE TITLE
Example playground doesn't open

### ISSUE THREAD

**Issue by o-az** [gvergnaud/ts-pattern#232]
**Describe the bug**

I tried visiting the first example:

https://codesandbox.io/p/devbox/ts-pattern-api-examples-bdy5p2?file=%2Fsrc%2Fexamples%2Fbasic.tsx

I get:
![image](https://github.com/gvergnaud/ts-pattern/assets/23618431/3f0f8969-09a0-40df-a874-4b9aba20d086)

Might be a good idea to switch to stackblitz

**Comment by gvergnaud** [comment]
It sucks because I can no longer access the code and I didn't save a copy anywhere, so I can't even migrate to something else without recreating these examples from scratch or paying for CodeSandbox 😢

**Comment by gvergnaud** [comment]
Thanks for reporting, I moved these examples over to Stackblitz
