### ISSUE TITLE
Add support for pattern matching class instances

### ISSUE THREAD

**Issue by not-rusty** [gvergnaud/ts-pattern#24]
Let's suppose we have the following types:

```typescript
class UserId {
    constructor(public val: string, private _?: string) {}
}

class SellerId {
    constructor(public val: string, private _?: string) {}
}

type Ids = UserId | SellerId
```

I've found that for nominal typing, a class with a private property is IMO the best and simplest way to achieve it. It is quite an advantage having both constructor and type on the same place. No `unique symbol` branding and no type casting on the constructor functions.

Also, as long as no inheritance shenanigans happen it allows to do strict pattern matching out of the box:

```typescript

const assertNever = (val: never): never => {
    throw new Error('Should never happen')
}

const processId = (id: Ids): string => {

    if (id instanceof UserId) {
        return 'this is a user id'
    } else if (id instanceof SellerId) {
        return 'this is a seller id'
    }

    return assertNever(id)
}
```

Sadly, I have to put an ugly assertNever at the end.

I just discovered this lib, and it would be quite nice to be able to pattern match those cases too without tedious `instanceof` chains.

A sample implementation would be something like:

```typescript
match(id)
    .with(UserId, (res) => 'UserId detected')
    .with(SellerId, (res) => 'SellerId detected')
    .exhaustive()
```

How difficult would it be to implement it?

**Comment by not-rusty** [comment]
As a side note, with the `.when` I can achieve what I proposed:

```typescript
const result = match(id)
    .when(
        (id): id is UserId => id instanceof UserId,
        () => console.log('user id')
    )
    .when(
        (id): id is SellerId => id instanceof SellerId,
        () => console.log('seller id')
    )
    .exhaustive()

```

But it's really verbose. A possible fix would be to make a helper function to create the predicates, but this is what I've tried and I had no luck:

```typescript
// Helper function
const matchClass = <T extends Function>(nominalType: T) => {
    return (val: T): val is T => val instanceof nominalType
}

const result = match<Ids>(id)
    .when(matchClass(UserId), () => console.log('user id'))
    .when(matchClass(SellerId), () => console.log('seller id'))
    // .when((id): id is UserId => id instanceof UserId, () => console.log('user id'))
    // .when((id): id is SellerId => id instanceof SellerId, () => console.log('seller id'))
    .exhaustive()

```

**Comment by gvergnaud** [comment]
Having an `instanceOf()` pattern for this use case would be an interesting idea (if it wasn't a reserved word).

in the meantime using `when` + an `isInstanceOf` helper function to create the predicate should work:

```ts
class UserId {
  constructor(public val: string, private _?: string) {}
}

class SellerId {
  constructor(public val: string, private _?: string) {}
}

type Ids = UserId | SellerId;

// Helper function
type AnyConstructor = new (...args: any[]) => any;

function isInstanceOf<T extends AnyConstructor>(nominalType: T) {
  return (val: unknown): val is InstanceType<T> => val instanceof nominalType;
}

const id = new UserId("") as Ids;

// This works fine
const result = match<Ids>(id)
  .when(isInstanceOf(UserId), (x) => console.log("user id")) // Both don't work
  .when(isInstanceOf(SellerId), (y) => console.log("seller id"))
  .exhaustive();
```

your `matchClass` function wasn't working because `val is T` states that val is the constructor, not an instance of this class. you need to use `val is InstanceType<T>` instead.

**Comment by gvergnaud** [comment]
Wait. Actually `instanceOf` isn't a reserved word, and we can actually already implement this type of pattern in userland by using `when` + the `isInstanceOf` function from my earlier message:

```ts
function instanceOf<T extends AnyConstructor>(nominalType: T) {
  return when(
    (val: unknown): val is InstanceType<T> => val instanceof nominalType
  );
}

const id = new UserId("") as Ids;

const result = match<{ id: Ids }>({ id })
  .with({ id: instanceOf(UserId) }, (x) => console.log("user id")) // Both don't work
  .with({ id: instanceOf(SellerId) }, (y) => console.log("seller id"))
  .exhaustive();
```

This is a bit more flexible because you can use it at any level in your pattern. I'll think about adding it to the lib

**Comment by not-rusty** [comment]
Thank you very much! I wasn't aware of the `InstanceType` utility, this is exactly what I needed.

**Comment by gvergnaud** [comment]
`instanceOf` pattern has been added in the latest pre release! https://github.com/gvergnaud/ts-pattern/releases/tag/v3.2.1-next.1
