### ISSUE TITLE
Feature: return the value directly

### ISSUE THREAD

**Issue by gideaoms** [gvergnaud/ts-pattern#246]
Hi, congratulations for the lib.

I would like to know if there is a possibility to return the value directly when I don't need to use it.

How it works today:
```ts
match(5)
  .when(1, () => "one")
  .when(2, () => "two")
  .otherwise(() => "three or greater")
```

How I would like it to work:
```ts
match(5)
  .when(1, "one")
  .when(2, "two")
  .otherwise("three or greater")
```

**Comment by darrylnoakes** [comment]
Duplicate of #100.

**Comment by gideaoms** [comment]
> Duplicate of #100.

Thanks for letting me know, I'll close it.
