### ISSUE TITLE
Issue: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by guyzmo** [gvergnaud/ts-pattern#26]
**Describe the bug**

I'm getting the following error:

```
Type instantiation is excessively deep and possibly infinite.
```

when doing the following pattern.

**Code Sandbox with a minimal reproduction case**

[You can find it here, though it does not shows the error I'm getting](https://www.typescriptlang.org/play?ssl=68&ssc=1&pln=1&pc=1#code/JYWwDg9gTgLgBAbziAhjAxgCwDRwM4CmANgevAL5wBmUEIcARDHgLRhowFQB2DA3ACgBwbpyhUU6AnAAKKKChABGACoBPMNIQC4uuMAAmALjjcAriABGXQXtOKCJvDCgiA5oPJCRYiVNnyigBM6pqIOnqGJuZWNhG6MBqO+C7unt6iXH7SACJoKAAywM4AkpwgoVrxcOwKyiZydapJtnq1wQ2BICEtAl7CmeKSufkA8pYAVqQwleF2BvlFziYAglAKagA8eTCFxTBlBBVJAHzpA77DcDsos9p2VBAQJjfjU2SzAD5wZtwGBFQRAQDK1dJZ5C8xpNpl8fn8AUCQX0hOgINxnHAFrtIbtZgBeOZ6R7POH-QHcYHYargqAme52PRYvbLOAAbWqDL09M5PJqXSUdI5vJ5UTgSipwsl9hAyQYAA8GBKpXZyErlbp2t1BeqRcYxWqdXpEpoTExMO5FULJV5laqrQykPbeZqBYTDZE9UEDe7uA5TWpLe67e7NUFte6PSYvU6pcbZTBzdw3IHDTapWnOQBdapefoAejzcC4tCgcBUAGUggBWAAcAE4TLMRM4UKJgGhgGj9Hgi3KpHg8MAAG7ENSYggEMBwVsGGoQAfASxEMcicnATgAOgEqPR8CgBDwZiI8AJqAwmAAFEyAJQCDcAd3Xl+qSGJJl+ZMRuBpdMxi32JisogfJ1GGwFxqaCYWnAqogYorqECQZAXteMFwJmMHBnoF4uqheInHBygCLeD5PheL5wD+wFMksMCAcBoa-hBjBQUmDAwbgLpOMQ0woWhGHkFhug4fyeEES6xF3hACZcI+hAXnx+GmEeRC3tuaJ4BAJAbkQEBuBe+6Hse16CEAA)

here's the match pattern:

```
// error TS2589: Type instantiation is excessively deep and possibly infinite.
const result = match(data)
.with(
    { foo: undefined, bar: { dataList: [ { param2: { type: "thing" }, param1: select() } ] }},
    (param1) => param1
)
.with(
    { bar: { dataList: [ { param2: { type: "thing" }, param1: select() } ] }},
    (param1) => param1
)
.otherwise(() => null)
```

If I simplify the first with pattern into:

```
    { foo: undefined, bar: { dataList: [ { param2: __, param1: select() } ] }},
```

the issue goes away, though my selection is wrong.

If I add:

```
// @ts-ignore TS2589
```

the compilation works fine.

**Versions**
- TypeScript version: 4.2.3
- ts-pattern version: 3.1.1
- environment:
   - lerna: 3.22.1
   - node: 5.12.0

thank you for your project :)

**Comment by gvergnaud** [comment]
Hello! 

I'm sorry but I can't have a look and try to resolve this issue if you don't provide a way to produce it. Could you try add a repro case were the error happens in code sandbox (or TS playground)? 

The fact that ts-pattern only supports up to 6 levels of nesting in a pattern is a known limitation. I'd love to find a way to increase this limit, but TS quickly throws this "Type instantiation is excessively deep" error.

**Comment by guyzmo** [comment]
how do you calculate the 6 levels of nesting?

I'll try to make a reproduceable pattern, though I don't know exactly what's causing this, and how to rebuild it.
My data is coming from GraphQL, which can be pretty deep at times :)

All in all, I was expecting an answer like that, but I guess it's a good idea to have an issue opened about that, to try to solve that and for future users ;-)

**Comment by guyzmo** [comment]
(given my other issue I finally rewrote the pattern in a more verbose, but accurate, way, and as a side-effect this is no longer an issue for me). So I'm closing this, and if someone runs into the same issue, you'll know that you have two options, at this stage:

* add a ts-ignore
* rewrite your pattern

🤷
