### ISSUE TITLE
Example in readme doesn't open

### ISSUE THREAD

**Issue by o-az** [gvergnaud/ts-pattern#266]
codesandbox still causing issues

I tried accessing the react gif fetcher example from the readme but it's not opening: https://github.com/gvergnaud/ts-pattern/blob/bfb3e68011f810a5f9343df4ba10d42e4c89f4fb/README.md?plain=1#L148

![image](https://github.com/gvergnaud/ts-pattern/assets/23618431/709e6321-d1e7-47e1-b2a2-e56ea71275b8)

even when I'm signed in (in the iOS app):

![image](https://github.com/gvergnaud/ts-pattern/assets/23618431/7f316be6-29c6-4723-8741-3d61f5851b57)

related previous issue
https://github.com/gvergnaud/ts-pattern/issues/232

**Comment by gvergnaud** [comment]
Thans I just moved the last two example over to stackblitz. Let me know if it works now
