### ISSUE TITLE
union type appears not to work with booleans (?)

### ISSUE THREAD

**Issue by sebpowell** [gvergnaud/ts-pattern#267]
Hello, 

Thank you for this library, I came across it recently – it looks great, and just trying to get to grips with it. 

As far as I understand, the `union` method will return true if **any** of the specified conditions return `true`. However, it seems to only work if **all** the conditions return true (which I believe is what the `intersection` method is supposed to do?).

I adapted one of the examples so it looks like this:

```TSX
type Response = {
  isLoading: boolean;
  isSuccess: boolean;
};

const testFunction = (response: Response) =>
  match(response)
    .with(
      // Here, I am able to access a prop ('randomProp') that doesn't exist, is there a way to avoid this happening?
      P.union({ isSuccess: true, isLoading: true, randomProp: true }),
      () => <>Show something...</>
    )
    .otherwise(() => null);

// This doesn't work, although it theoretically should?
export const UnionOne = () => {
  const input: Response = {
    isLoading: false,
    isSuccess: true,
  };

  return <div>One: {testFunction(input)}</div>;
};

// This works, although in theory we shouldn't need both props to be set to true?
export const UnionTwo = () => {
  const input: Response = {
    isLoading: true,
    isSuccess: true,
  };

  return <div>Two: {testFunction(input)}</div>;
};

```

The above is available here: https://stackblitz.com/edit/vitejs-vite-34h3xp?file=src%2Fexamples%2Funion.tsx. 

Thank you in advance.

**Comment by sebpowell** [comment]
Just worked it out – sharing the solution in case it helps someone else. 

It seems you need to use a custom predicate – this works:

```TSX
const testFunction = (response: Response) =>
  match(response)
    .with(
      P.when(({ isSuccess, isLoading }) => isSuccess || isLoading),
      () => <>Show something...</>
    )
    .otherwise(() => null);    
```

**Comment by gvergnaud** [comment]
I'd probably do something like this:

```ts
const testFunction = (response: Response) =>
  match(response)
    .with(
      { isSuccess: true },
      { isLoading: true },
      () => <>Show something...</>
    )
    .otherwise(() => null);
```

You can pass several patterns to .with(...), with the same semantics as `P,union`, so if either pattern matches, this branch is chosen.

**Comment by sebpowell** [comment]
@gvergnaud ah brilliant, I will try that – much cleaner / simpler, thank you so much.
