### ISSUE TITLE
can't infer types from Pattern generic

### ISSUE THREAD

**Issue by sun0day** [gvergnaud/ts-pattern#268]
**Describe the bug**

Maybe it's not a bug, but it's kind of weird that can't infer types from `Pattern` generic

```ts
import {Pattern, P} from 'ts-pattern'

function f(p: Pattern.Pattern<{a: boolean}> = {a: P.boolean}) {
  const d: Pattern.Pattern<{ a: boolean }> = { a: P.boolean }
  console.log(d.a) // good
  console.log(p.a) // error, p.a not exist
}
```

**TypeScript playground with a minimal reproduction case**

Example: [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwAoEMYwKZQHYBo5IC+cAZlBCHAOQwDOAtGGpjlQFBskCu2AxjMAjZSACjAAuAsyzYAdKnQyAPAhSSARhAgAbDCmyEAfHAC8iNQVmadegwEpEbOHF5Da8ACaSFLOT+UIcBbWuvpwRqaIQd5WWqHChE4ubjay2hAA5iIesigOAPT5cBlaHkmu2LSp6VlguQVFWORQ+NgQ8BgAHsDubIRAA)

**Versions**
- TypeScript version: 5.5.3
- ts-pattern version: latest
- environment: chrome

**Comment by gvergnaud** [comment]
Hey, that's expected. A pattern doesn't have to be an object of the same shape. For example a `P.when(...)` pattern would be assignable to `Pattern.Pattern<{a: boolean}>` and wouldn't have any of the properties of the object that you want to match on.

if you want to make sure that an object is assignable to a pattern of a certain type, take a look at the satisfies keyword:

```ts
const x =  { a: P.boolean } satisfies Pattern.Pattern<{ a: boolean }>
```
