### ISSUE TITLE
Matching any value in an Array pattern

### ISSUE THREAD

**Issue by guyzmo** [gvergnaud/ts-pattern#27]
**Is your feature request related to a problem? Please describe.**

I'm trying to match a pattern within an array:

```
const foobar = [
  {
    bar: 1,
    test: true
  },
  {
    bar: 2,
    test: true
  }
]
```

and the pattern is:

```
match(foobar)
  .with([{bar: select(), test: true}])
  .otherwise(() => "fail")
```

when `foobar.foo.test` is all true, the output is `[1, 2]`
if there's at least one `false`, the output is `fail`.

So the pattern, when applied on a list, is matching when all elements of the list match, and does not match when all the element don't. If it was an array method, it's behaving like an `Array.prototype.every`.

**Describe the solution you'd like**

**_Naively_**, when I wrote the code, I expected it to behave like an `Array.prototype.filter`, meaning that given:

```
const foobar = [
  {
    bar: 1,
    test: true
  },
  {
    bar: 2,
    test: false
  },
  {
    bar: 3,
    test: true
  }
]
```

The output I _naively_ expected was `[1, 3]` and not `"fail"`. Then I went back to [RTFM](https://github.com/gvergnaud/ts-pattern#lists-arrays) and saw how I was mistaken. But still, I believe that behaviour would be desirable.

**Describe alternatives you've considered**

The solution to that would be to chain/nest the match() calls, or go back to the good old `Array.prototype.filter`.

I went for a solution alike:

```
match(foobar)
  .with(
    [{bar: select('bars'), test: select('tests')}],
    ({bars, tests}) => bars.filter((, i) => tests[i]).map(({bars}) => bars)
  )
  .otherwise(() => "fail")
```

Maybe a decent (and backward compatible) syntax could be adding an `any` guard like:

```
match(foobar)
  .with([{bar: select(), test: any(v => !value)}])
```

that would work alike the `when()` guard function, but selecting items of a list instead of matching them all.
(It could be also called `filter` or `some` to sound like JS functions).

**Additional context**

I'm discovering this module, and I'm excited about it (years of ocaml in the past, and now working in elixir in parallel made me addicted to pattern matching 😄 ), so  I hope you don't mind me shooting issues and share my thoughts as a newcomer.

I made a little MCVE: https://codesandbox.io/s/ts-pattern-list-match-2m9h9

Do you think this would be implementable (the way I'm expecting, or another way)?

**Comment by gvergnaud** [comment]
👋 

Thanks for suggesting this feature, but I think the current behavior is preferable to making the pattern behave like a filter on arrays. Imho, patterns are just a declarative way to validate that the input data structure (as a whole) respect a condition, not a way to filter the input.

I want patterns to behave similarly for every data structures, and implementing this would mean treating arrays differently from other inputs, which I don't think is a good idea

**Comment by guyzmo** [comment]
I do understand your position, though I do believe the use case of finer grained matches on arrays could prove useful.
My suggestion wasn't probably the best way, I have to admit I was focused on one application, not in the generalisation.

And we could come up with other ways inspired by other functional languages approaches to this class of problems, though IIRC, that might imply a recursive function with a head, ...tail destructuring approach.

----

BTW, on a side note, it might be a good idea to have some place to write a list of interesting patterns, real life inspired use cases, as a repository of ideas, good practices, solutions to specific problems and tips & tricks. The issues of that project is not the place to go for that, and definitely this issue is neither. After sometimes using it in production, I guess I'll make at least a blog article once I got enough experience and material.

Maybe could you open the `discussions` part of github for that?
And/or maybe open a chat channel (IRC, Matrix, Gitter, Slack...)?

**Comment by gvergnaud** [comment]
> And we could come up with other ways inspired by other functional languages approaches to this class of problems, though IIRC, that might imply a recursive function with a head, ...tail destructuring approach.

I think this would be a good approach, I'm planing to add a `rest` pattern which would match the tail of a list, you can find an example of what it would look like in the [ROADMAP.md](https://github.com/gvergnaud/ts-pattern/blob/master/ROADMAP.md). Let me know what you think

>  it might be a good idea to have some place to write a list of interesting patterns, real life inspired use cases, as a repository of ideas, good practices, solutions to specific problems and tips & tricks.

That's a great suggestion! 

Something I'd like to do would be to add an `examples` folder open to contributions on this repo. It would be really nice if it could be automatically synced with code sandbox to make them interactive and forkable. I'll try to find the time to do that during the weekend

**Comment by guyzmo** [comment]
that's pretty neat, though in the example, I believe you meant that `reverse()` and `reverse2()` are the same function, for recursion. And I believe there can be heap explosion if the list is a bit too big 😆
