### ISSUE TITLE
Support for own primitive types like UUID or Email

### ISSUE THREAD

**Issue by nkoehring** [gvergnaud/ts-pattern#288]
**Is your feature request related to a problem? Please describe.**

I started narrowing strings down to specific types, like Email and UUID. I didn't find a way to describe such types using P/pattern.

**Describe the solution you'd like**

I'd like to add my own type guards, like:

```ts
const pattern = {
  id: isUUID
}
type PatternType = P.infer<typeof pattern>
```

and get a type `{ id: UUID }`. Instead right now I get `{ id: (value: string) => value is UUID }`

**Describe alternatives you've considered**

Currently, I use P.string and check specific strings separately.

**Comment by gvergnaud** [comment]
You can use `P.when(isUUID)` for that: https://github.com/gvergnaud/ts-pattern?tab=readme-ov-file#pwhen-patterns
