### ISSUE TITLE
`__.empty/none` pattern

### ISSUE THREAD

**Issue by m-rutter** [gvergnaud/ts-pattern#29]
**Is your feature request related to a problem? Please describe.**
Sometimes something can be a union of `null | undefined | T`. This comes up quite often in graphql projects where `null` and `undefined` are basically interchangable. If you use something like graphql-codgen then the codegen interfaces and types will be littered with stuff like this:

```ts
type Maybe<T> = null | T;

type SomeGraphqlType = {
  __typename: "SomeGraphqlType",
  id: Scalars["ID"],
  foo?: Maybe<SomeOtherGraphqlType | YetAnotherGraphqlType> 
}

type SomeOtherGraphqlType = {
  __typename: "SomeOtherGraphqlType"
}

type YetAnotherGraphqlType= {
  __typename: "YetAnotherGraphqlType"
}
```

Sometimes these nullable unions can be quite large, and so you just want to check if its null/undefined and then maybe later match on that union in some other code branch.

Right now you can do `match(x).with(not(undefined), not(null), () => {})`, which works find, but sometimes that can be a bit laborious if what you want to match on in a little more complex than the above example, such as when you want to match against multiple nullable fields at lots of different depths.

**Describe the solution you'd like**
A `__.empty` or `__.none` pattern that matches `null | undefined`. Allowing a user to write this:
```ts
match(x).with({y: not(__.empty)}, ({y}) => {
  // y is not `null | undefined`
});
```

**Describe alternatives you've considered**
Alternatives are:
Use a `when` with a type guard that takes a `null | undefined | T` and returns `x is T`
Provide multiple patterns, one of which is `not(undefined)` and the other which is `not(null)`.

**Additional context**
https://www.graphql-code-generator.com/

**Comment by gvergnaud** [comment]
👋 I think this should be doable in user land using `when`:

```ts
const nullable = when(
  (x: unknown): x is null | undefined => x === null || x === undefined
);

match<{ str: string } | null>({ str: "hello" })
  .with(not(nullable), ({ str }) => str)
  .with(nullable, () => "")
  .exhaustive();
``` 

However I just noticed a bug with `not`. It seems that it isn't able to correctly invert the type of a `when` pattern containing a type guard so currently when you do `not(nullable)` on some input of type `string | null` the type isn't correctly refined to `string` and instead you get `string | null`. I'll try to fix this in the next patch release

**Comment by gvergnaud** [comment]
I just publish version `3.1.3` which fixes the issue described above, so using this definition of `nullable/empty/none` should do the trick:

```ts
const nullable = when(
  (x: unknown): x is null | undefined => x === null || x === undefined
);

```

**Comment by m-rutter** [comment]
> I just publish version `3.1.3` which fixes the issue described above, so using this definition of `nullable/empty/none` should do the trick:
> 
> ```ts
> const nullable = when(
>   (x: unknown): x is null | undefined => x === null || x === undefined
> );
> ```
> 
> [Sandbox](https://codesandbox.io/s/not-nullable-example-pz7xm)

**Comment by m-rutter** [comment]
@gvergnaud I didn't quite mean to close the issue.

Thanks, your solution worked. I do think its quite likely I'm going to be using your nullable example quite a bit.
