### ISSUE TITLE
Type 'GuardPattern<unknown, string>' is not assignable to type 'string'

### ISSUE THREAD

**Issue by llldar** [gvergnaud/ts-pattern#41]
**Describe the bug**
ts error  Type 'GuardPattern<unknown, string>' is not assignable to type 'string'
when trying to match a union type

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/serene-night-hdl54?file=/src/index.ts

**Versions**
- TypeScript version: 4.3.5
- ts-pattern version: 4.2.2
- environment: browser

**Comment by gvergnaud** [comment]
Thanks for reporting, fixed in v3.2.3: https://codesandbox.io/s/determined-mayer-r8556
