### ISSUE TITLE
Matching a Narrowed Generic

### ISSUE THREAD

**Issue by themooer1** [gvergnaud/ts-pattern#47]
**Describe the bug**
Matching a function parameter which has been narrowed to a specific string fails to type-check.  If I predefine a type with exactly one value, it can be matched.  Perhaps I'm misunderstanding how narrowing works?

```
// Pre-defining the type works :)
type A = "A";
function specific(tryType: A) {
  match(tryType)
    .with(tryType, () => console.log("This should match :)"))
    .exhaustive();
}

// But matching an generic type fails :(
function generic<TRY extends string>(tryType: TRY) {
  match(tryType)
    .with(tryType, () => console.log("This should match :)"))
    .exhaustive();

  // Even though TRY can only have one value 
  //  vvvvv (Does not type-check)
  const t: TRY = "this fails, because TRY was narrowed to one value";
}
```

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/boring-dewdney-pnxm8?file=/src/index.ts

**Versions**
- TypeScript version: 4.4.3
- ts-pattern version: 3.2.5
- environment: node version

Thanks for your attention, and all the time you put into this project!

**Comment by gvergnaud** [comment]
👋 Unfortunately matching on generic type isn't possible, it's a know limitation of `ts-pattern`. The reason is that generic types (like `Pattern<A> = ...`) don't reduce on unknown type parameters, so if you try to match on an unknown type parameters, the inference will get stuck.

You can match on types containing type parameters though, like in this example:
```ts

function f<T>(input: { type: 'a', value: T } | { type: 'b' }) {
  return match(input)
    .with({ type: 'a' }, () => ...)
    .with({ type: 'a' }, () => ...)
    .exhaustive();
}
```

But you can't match on `T` directly.

**Comment by themooer1** [comment]
That makes perfect sense!  Thanks!

**Comment by taneba** [comment]
@gvergnaud 
Hi, sorry for asking in a closed issue, but is this not working for the same reason?

```
type Ok<T> = { type: 'ok'; data: T }
type Err<E> = { type: 'error'; error: E }
type AppError = 'ERROR_A' | 'ERROR_B' //  C,D,...
type Result<T, E extends > = Ok<T> | Err<E>

// I want to reuse "ERROR_A" matcher for reduce repetitive code
const matchResult = <T extends Result<any, AppErrorType>>(result: T) =>
  match(result).with({ type: 'error', error: 'ERROR_A' }, () => {
    throw new Error('database error')
  })
```

It causes error: `Argument of type '{ type: "error"; error: "DATABASE"; }' is not assignable to parameter of type 'Pattern<T>'.`

**Comment by gvergnaud** [comment]
Yes it's the same issue
