### ISSUE TITLE
select() of optional fields breaks exhaustiveness

### ISSUE THREAD

**Issue by jsarafajr** [gvergnaud/ts-pattern#51]
**Describe the bug**
When adding select() to a pattern field which type is optional ts-pattern thinks it's no longer exhaustive

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/nameless-wood-bfwi4?file=/src/index.ts

```typescript
import { match, select } from "ts-pattern";

type Action =
  | { type: "one" }
  | { type: "two"; data?: string } // works ok when changing to `data: string`
  | { type: "three" };

declare const action: Action;

match<Action>(action)
  .with({ type: "one" }, () => {})
  .with({ type: "two", data: select() }, () => {})
  .with({ type: "three" }, () => {})
  .exhaustive();
```

**Versions**
- TypeScript version: 4.3.3
- ts-pattern version: 3.3.3

**Comment by gvergnaud** [comment]
Hey! That's expected, your pattern is no longer exhaustive if you use `select()`, because objects which don't have a data property won't match this pattern. Here is a playground explaining what I mean: https://codesandbox.io/s/ecstatic-spence-ugfp4?file=/src/index.ts

**Comment by jsarafajr** [comment]
Hmm, got it, thanks for the quick reply.
