### ISSUE TITLE
ts-pattern doesn't compile with typescript 4.5.0-beta

### ISSUE THREAD

**Issue by m-rutter** [gvergnaud/ts-pattern#59]
**Describe the bug**
It appears that ts-pattern project itself doesn't compile with the 4.5.0-beta. You get various errors around stack depth and non-assignablilty.

In my own project using ts-pattern 3.3.3, when I tried to upgrade to 4.5.0-beta I hit excessive stack depth errors on code that previously compiled in 4.4.4.

**Code Sandbox with a minimal reproduction case**
I haven't been able to create a simple reproduction of consuming v3.3.3 using 4.5.0-beta. I will update when I can easily reproduce in an isolated way.

**Versions**
- TypeScript version: 4.5.0-beta
- ts-pattern version: 3.3.3

**Comment by gvergnaud** [comment]
Thanks for reporting!

 It looks like TS v4.5.0-beta isn't able to solve non trivial type constraints anymore. For example [FindUnions](https://github.com/gvergnaud/ts-pattern/blob/2584b28ef41c4b085ef238271f6b315e64d0aa68/src/types/DistributeUnions.ts#L77) always returns a tuple type but when passing its result to a generic type taking a parameter with a constraint `any[]`, the compiler now complains. Weird.


![image](https://user-images.githubusercontent.com/9265418/139660688-5eee88e0-2841-40a3-8de8-a49999ffcb95.png)

**Comment by gvergnaud** [comment]
This has been fixed in the RC 🥳 🎉  https://github.com/microsoft/TypeScript/issues/46631

**Comment by m-rutter** [comment]
Thank goodness for that!
