### ISSUE TITLE
Add __.valued wildcard

### ISSUE THREAD

**Issue by mordv** [gvergnaud/ts-pattern#60]
Hi! Thanks for this amazing library!

I often use `{x: not(__.nullish)}` pattern so I wonder can we add `__.valued` wildcard?

Which would look like this 
```ts
const isValued = <T>(val?: T | null | undefined): val is T => val !== undefined && val !== null;
```

Happy to create PR, if you approve.

**Comment by gvergnaud** [comment]
Thanks for the suggestion, I'll consider it. In the meantime, since this can be implemented in user land with `when(isValued)`, you can store this in your own codebase if you want to use this

**Comment by JUSTIVE** [comment]
I think this issue is ok to close
