### ISSUE TITLE
Types don't narrowed with class hierarchy

### ISSUE THREAD

**Issue by i-have-no-name** [gvergnaud/ts-pattern#68]
**Describe the bug**
Hey. Maybe I do something wrong :)
When using class hierarchy with `instanceOf`, `match` always select a base class or wildcard.
In my case, I am expecting a narrowed type and choice of `with (instanceOf(CException))`.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/confident-bose-ru6zw?file=/src/index.ts

**Versions**
- TypeScript version: 4.4.4
- ts-pattern version: 3.3.4
- environment: node 14.15.0

**Comment by gvergnaud** [comment]
👋 
`instanceOf` is a simple wrapper around the `instanceof` keyword, and apparently `new CException() instanceof CException` evaluates to false for your class hierarchy, which is pretty weird. It looks like it's coming from the fact your are extending the `Error`: 


```ts
class AException extends Error {}
class BException {}

const a = new AException()
const b = new BException()

a instanceof AException // => false
b instanceof BException // => true
```

This stackoverflow issue seems relevant: https://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node

**Comment by i-have-no-name** [comment]
Yeap. You are right. I don't use babel, but if change `target` for in `tsconfig` to es6, everything works great. Thanks.
