### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite when using select()

### ISSUE THREAD

**Issue by nidomiro** [gvergnaud/ts-pattern#72]
**Describe the bug**
If i use `select()` in a with statement Typescript complains with `TS2589: Type instantiation is excessively deep and possibly infinite.`

May relate to #26

**Code**
https://github.com/nidomiro/ts-tools/blob/4d5fe22e5a1a32d859491da8af050c1c33834c34/packages/config-helper/src/lib/config-default-impl.ts#L80
```ts
match(transformedValue)
	.with({ error: NotConvertable }, () =>
		err({
			errorType: NotConvertable,
			propertyPath,
			inputValue: value,
		} as SchemaError),
	)
	.with({ value: select() }, (value) => ok(value))
	.exhaustive()
```
If I remove the line `.with({ value: select() }, (value) => ok(value))` this TS-error goes away.

**Versions**
- TypeScript version: 4.3.5
- ts-pattern version: 3.3.4
- environment: node 16

**Comment by gvergnaud** [comment]
The depth limit for recursive types has been increased in TS v4.5, did you try upgrading?

Without a sandbox it's hard for me to debug and provide better insight on what might be happening unfortunately

**Comment by nidomiro** [comment]
Thanks @gvergnaud  for the quick response

TS v4.5 did not help, but I managed to write a minimal codesandbox example: https://codesandbox.io/s/jolly-microservice-qqpq6?file=/src/index.ts

**Comment by gvergnaud** [comment]
Oh I didn't understand you were trying to pattern match on a generic type. it's isn't supported because type level functions don't evaluate on generics unfortunately, that's why you are seing this error. you could maybe use a `.when(isOk, handler)` instead?

**Comment by nidomiro** [comment]
Thanks for the clarification @gvergnaud.
Unfortunately I had no luck in finding an alternative solution...

```ts
.with({ error: not(__) }, (result) => ok(result.value))
```
and

```ts
.when(o => o.isOk(), (result) => ok(result.value))
```

are both missing the smart cast and the exhaustive check is also failing.

It seems that I have to use the good old if statement instead :(
