### ISSUE TITLE
Does this library work with webpack?

### ISSUE THREAD

**Issue by johnknoop** [gvergnaud/ts-pattern#75]
Using webpack@4.46.0 and typescript@4.50, I get this error:

> ERROR in ./node_modules/ts-pattern/lib/index.js
> Module not found: Error: Can't resolve './guards' in 'C:\work\zwiftly\source\Zwiftly.WebApp\node_modules\ts-pattern\lib'
>  @ ./node_modules/ts-pattern/lib/index.js 5:17-36
>  @ ./app/app.ts
> 
> ERROR in ./node_modules/ts-pattern/lib/index.js
> Module not found: Error: Can't resolve './symbols' in 'C:\work\zwiftly\source\Zwiftly.WebApp\node_modules\ts-pattern\lib'
>  @ ./node_modules/ts-pattern/lib/index.js 4:16-36
>  @ ./app/app.ts
> 
> ERROR in ./node_modules/ts-pattern/lib/index.js
> Module not found: Error: Can't resolve './wildcards' in 'C:\work\zwiftly\source\Zwiftly.WebApp\node_modules\ts-pattern\lib'
>  @ ./node_modules/ts-pattern/lib/index.js 10:20-42
>  @ ./app/app.ts

I haven't seen this in other projects where I'm using ts-pattern. I'm sure it can't be a bug, because other people would have stumbled on it before me. But I'm not really sure what to do. I've tried searching the issues here in your repo, but came up blank.

Any ideas?

My ts.config looks like this:

```ts
{
	"compilerOptions": {
		"module": "ES6",
		"removeComments": true,
		"sourceMap": true,
		"lib": [ "es2017", "dom" ],
		"strictNullChecks": false,
		"moduleResolution": "node",
		"target": "es5",
		"noResolve": false,
		"allowSyntheticDefaultImports": true,
		"baseUrl": ""
	},
	"include": [
		"app/**/*.ts",
		"typings/BackendApi/*.ts"
	],
	"exclude": [
		"app/specs/**/*.ts"
	],
}
```
and my webpack configuration looks like this:
```js
// webpack.common.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
	entry: './app/app.ts',
	module: {
		rules: [
			{
				test: /\.ts$/,
				use: 'ts-loader',
				exclude: /node_modules/
			}
		]
	},
	resolve: {
		extensions: ['.ts']
	},
	plugins: [
		new CleanWebpackPlugin(),
		new HtmlWebpackPlugin({
			filename: path.resolve(__dirname, './Views/Home/Index.cshtml'),
			template: './Views/Home/Index.template.cshtml',
			inject: false
		})
	],
	output: {
		filename: '[name].[contenthash].bundle.js',
		path: path.resolve(__dirname, 'js'),
		publicPath: '/'
	},
	optimization: {
		splitChunks: {
			cacheGroups: {
				vendor: {
					test: /[\\/]node_modules[\\/]/,
					name: 'vendor',
					chunks: 'all'
				}
			}
		}
	}
};

// webpack.dev.js
const merge = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
	mode: 'development',
	devtool: 'inline-source-map',
	watch: true
});
```

**Comment by johnknoop** [comment]
@gvergnaud I've created a minimal example repo with `webpack`, `typescript` and `ts-pattern` as the only dependencies.

Please have a look if you have the time: https://github.com/johnknoop/ts-pattern-test

**Comment by johnknoop** [comment]
I tried upgrading webpack to the latest version, but that didn't help.

Has anyone actually succesfully used `ts-pattern` with webpack? 🤔

**Comment by gvergnaud** [comment]
Yes, I'm using ts-pattern with webpack everyday at work. I don't know why your config isn't working as expected though, I unfortunately don't have the time to investigate

**Comment by johnknoop** [comment]
That is really weird. I thought maybe there's something wrong with my `tsconfig.json` then, so I deleted it and generated a new one with `yarn tsc --init` but still the same error.

**Comment by paul-sachs** [comment]
@johnknoop i think the problem is your extensions. You've only got .ts. I would add .js as well.

**Comment by johnknoop** [comment]
> @johnknoop i think the problem is your extensions. You've only got .ts. I would add .js as well.

Not sure I follow. Why would you add .js versions of the file? That's what `tsc` does (via webpack in this case).

**Comment by johnknoop** [comment]
@paul-sachs  Oh wait, now I see what you're saying. You're absolutely right! That did the trick :) Thanks a lot!

**Comment by paul-sachs** [comment]
@johnknoop Ah yeah, i should have been more specific, it's what i get for browser GitHub on my phone. It's the webpack config that needs updating:

```js
module.exports = {
	...,
	resolve: {
		extensions: ['.ts', '.js']
	},
}
```

Glad you figured it out.
