### ISSUE TITLE
Ability to select() tuple element as a whole

### ISSUE THREAD

**Issue by MikelArnaiz** [gvergnaud/ts-pattern#76]
Consider an input made of tuples + enums

```ts
enum Foo { ... }
enum Bar { ... }
type State = 
  | [Foo.A, Bar.A, {age: number}]
  | [Foo.A, Bar.B, {name: string, age: number}]
```

Note I'm using the last tuple element for the data, when patter matching I use a wildcard on it. Then I destructure the handler  selections to access `data`

```ts
.with([Foo.A, Bar.A, __], ([_foo, _bar, data]) => {
  // do something with data
})
.with([Foo.A, Bar.B, __], ([_foo, _bar, data]) => {
  // do something with data
})
```

The only workaround with `select` I know is to list all `data`'s properties

```ts
.with([Foo.A, Bar.A, { age: select('age')}], (data) => {
  // ...
})
.with([Foo.A, Bar.B, { name: select('name'), age: select('age') }], (data) => {
  // ...
})
```

**Describe the solution you'd like**

It would be great to select the wildcarted element

```ts
.with([Foo.A, Bar.A, __.select], (data) => {
  // ...
})
.with([Foo.A, Bar.B, __.select], (data) => {
  // ...
})
```

**Describe alternatives you've considered**
A workaround I'm using is to move the selection outside the pattern matching, but this doesn't act as a wildcard and only works if multiple cases have same `data`

```ts
const selectData = {
  name: select('name'),
  age: select('age')
}

...

.with([Foo.A, Bar.A, selectData], (data) => {
  // ...
})
.with([Foo.A, Bar.B, selectData], (data) => {
  // ...
})
```

**Comment by gvergnaud** [comment]
Hey, I believe you can already do this with the current version. Here is a sandbox demonstrating this: 

https://codesandbox.io/s/broken-frog-wmx243?file=/src/index.ts
