### ISSUE TITLE
Optional (1 to n) wildcard for tuples

### ISSUE THREAD

**Issue by MikelArnaiz** [gvergnaud/ts-pattern#77]
I have a complex scenario.

**Is your feature request related to a problem? Please describe.**

While pattern matching a tuple with wildcards I need to define all possible scenarios although I only care about the 1st element in the tuple.

I built a complex type to show it

```ts
enum Example1 { A = 'Example1-A', B = 'Example1-B', C = 'Example1-C'}
enum Example2 { A = 'Example2-A', B = 'Example2-B', C = 'Example2-C'}
enum Example3 { A = 'Example3-A', B = 'Example3-B', C = 'Example3-C', }
enum Example4 { A = 'Example4-A', B = 'Example4-B', C = 'Example4-C', D = 'Example4-D' }
enum Example5 { A = 'Example5-A', B = 'Example5-B' }

type Data = { foo: number };
type ExampleState =
  | 'nodata'
  | [Example1.A, Data]
  | [Example1.B, Example2, Example3, Data]
  | [Example1.C, Example2.A, Example3.A]
  | [Example1.C, Example2.A, Example3.B, Data]
  | [Example1.C, Example2.A, Example3.C, Data]
  | [Example1.C, Example2.B, Example3, Data]
  | [Example1.C, Example2.C, Example3.A, 'none', Data]
  | [Example1.C, Example2.C, Example3.A, Example4.A, Data]
  | [Example1.C, Example2.C, Example3.C, Example5, Data];
```

Then I pattern match with several `__`

```ts
export function getExample(input: ExampleState) {
  const foo = () => 'foo';

  return (
    match<ExampleState, string>(input)
      .with('nodata', foo)
      .with([Example1.A, __], foo)
      .with([Example1.B, __, __, __], foo)
      .with([Example1.C, __, __], foo)
      .with([Example1.C, __, __, __], foo)
      .with([Example1.C, __, __, __, __], foo)
      .exhaustive()
  );
}
```

Note the last 3 cases checks for the first element to be `Example1.C`.

**Describe the solution you'd like**
I'd like to define just once the case for `Example1.C`

Either with a new wildcard `__.optional`, `____` or an array `...__.array` if that's lazy and possible.

So 
```ts
match<ExampleState, string>(input)
      .with('nodata', foo)
      .with([Example1.A, __], foo)
      .with([Example1.B, __.oneToN], foo)
      .with([Example1.C, __.oneToN], foo)
      .exhaustive()
```

**Describe alternatives you've considered**
I tried with `.when()` but `TS` crashes. 

> Type instantiation is excessively deep and possibly infinite.

```ts
type IsExample1A = Extract<ExampleState, [Example1.A, ...unknown[]]>;
type IsExample1B = Extract<ExampleState, [Example1.B, ...unknown[]]>;
type IsExample1C = Extract<ExampleState, [Example1.C, ...unknown[]]>;

export function getExample(input: ExampleState) {
  const foo = () => 'foo';

  return (
    match<ExampleState, string>(input)
      .with('nodata', foo)
      .when((value): value is IsExample1A => value !== 'nodata' && value[0] === Example1.A, foo)
      .when((value): value is IsExample1B => value !== 'nodata' && value[0] === Example1.B, foo)
      .when((value): value is IsExample1C => value !== 'nodata' && value[0] === Example1.C, foo)
      .exhaustive()
  );
}
```

I think `.when` doesn't narrow down the type, does it?
In the second `.when` the type is still `ExampleState` and not `Exclude<ExampleState, IsExample1A | 'nodata'>`

![image](https://user-images.githubusercontent.com/2076221/156410842-e7343cd4-6d15-4055-874c-50b22195d8f5.png)

**Comment by gvergnaud** [comment]
Hey!

`P.optional` will be introduced in [ts-pattern v4](https://github.com/gvergnaud/ts-pattern/pull/70), although it won't work well with tuple patterns because ts-pattern always starts by checking if the length of the input array matches the length of the pattern. The idea of adding a `...rest` pattern is interesting, but probably a bit challenging to implement.

I feel like the complexity of your example arises from the data format you have chosen to store your state. Have you considered using objects rather than tuples?

**Comment by MikelArnaiz** [comment]
> I feel like the complexity of your example arises from the data format you have chosen to store your state. Have you considered using objects rather than tuples?

Yes I did but I liked the concise text of tuples. It allow for single line `.width`.

Regarding `P.optional`, I don't think I even needed. With an object the following compiles.

```ts
enum Example1 { A = 'Example1-A', B = 'Example1-B', C = 'Example1-C'}
enum Example2 { A = 'Example2-A', B = 'Example2-B', C = 'Example2-C'}
enum Example3 { A = 'Example3-A', B = 'Example3-B', C = 'Example3-C', }
enum Example4 { A = 'Example4-A', B = 'Example4-B', C = 'Example4-C', D = 'Example4-D' }
enum Example5 { A = 'Example5-A', B = 'Example5-B' }

type Data = { foo: number };
type ExampleState =
  | { ex1: Example1.A, data: Data }
  | { ex1: Example1.B, ex2: Example2, ex3: Example3, data: Data }
  | { ex1: Example1.C, ex2: Example2.A, ex3: Example3.A }
  | { ex1: Example1.C, ex2: Example2.A, ex3: Example3.B, data: Data }
  | { ex1: Example1.C, ex2: Example2.A, ex3: Example3.C, data: Data }
  | { ex1: Example1.C, ex2: Example2.B, ex3: Example3, data: Data }
  | { ex1: Example1.C, ex2: Example2.C, ex3: Example3.A, ex4: 'none', data: Data }
  | { ex1: Example1.C, ex2: Example2.C, ex3: Example3.A, ex4: Example4.A, data: Data }
  | { ex1: Example1.C, ex2: Example2.C, ex3: Example3.C, ex5: Example5, data: Data }

export function getExample(input: ExampleState) {
  return match<ExampleState, string>(input)
    .with({ ex1: Example1.A }, () => "It's 1A")
    .with({ ex1: Example1.B }, () => "It's 1B")
    .with({ ex1: Example1.C }, () => "It's 1C")
    .exhaustive()
}
```

I'm a bit surprised, I was expecting I would need to define all possible properties and `P.optional(__)`.

```ts
.with({ ex1: Example1.A, ex2: P.optional(__) , ex3: P.optional(__), ex4: P.optional(__), ex5: P.optional(__), data: P.optional(__) }, () => "It's 1A")
...
```

That's actually what I had to do with the tuples, is it because what you said?

> ts-pattern always starts by checking if the length of the input array matches the length of the pattern.

 I'll reconsider using objects.

**Comment by gvergnaud** [comment]
Closing because this is solved by [variadic tuple patterns](https://github.com/gvergnaud/ts-pattern#matching-variadic-tuples-with-parray):

```ts
match<ExampleState, string>(input)
      .with('nodata', foo)
      .with([Example1.A, ...P.array()], foo)
      .with([Example1.B, ...P.array()], foo)
      .with([Example1.C, ...P.array()], foo)
      .with([Example1.C, ...P.array()], foo)
      .with([Example1.C, ...P.array()], foo)
      .exhaustive()
```
