### ISSUE TITLE
Incorrect type of handler function when matching an array with select()

### ISSUE THREAD

**Issue by philer** [gvergnaud/ts-pattern#79]
I'm doing some simple route matching. Basically I'm splitting a path into an array of strings and extracting some parameters. Example:
```ts
const matchPath = (path: string) =>
  match(path.split("/"))
    .with(["users", select()], (name: string) => `username: ${name}`)  // error: Type 'string[]' is not assignable to type 'string'
    .run()

console.log(matchPath("users/bob"))  // works as intended, logging "username: bob"
```
In this example, the handler on the users route is supposed to take a `string` as the selected `name` parameter, however `tsc` insists that it's actually receiving `string[]`. It works fine at run time, only the type checker is complaining.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/infallible-hill-igwocg?file=/src/index.ts
Note that this works as intended, only type checking fails – It looks like code sandbox does not show typing errors.

**Versions**
- TypeScript version: 4.5.5
- ts-pattern version: 3.3.5

**Comment by gvergnaud** [comment]
Thanks I'll look into this. A simple work around is to use `as const` on your pattern: 

```ts
 .with(["users", P.select()] as const, (name) => `username: ${name}`)
```

It also looks like it's fixed in TS-Pattern v4 #70 : https://codesandbox.io/s/dawn-fire-bw4hgj?file=/src/index.ts:141-205

**Comment by philer** [comment]
Adding `as const` didn't work for me in v3, but upgrading to v4 solved it, as you mentioned. I'll just stick with v4, then.

Thanks a lot. Great library!

**Comment by gvergnaud** [comment]
Closing since TS-Pattern v4 has been released and fix this issue. [Release note](https://github.com/gvergnaud/ts-pattern/releases/tag/v4.0.1)
