### ISSUE TITLE
Document difference between .run() and .exhaustive()

### ISSUE THREAD

**Issue by philer** [gvergnaud/ts-pattern#83]
As far as I understand, the difference between `.run()` and `.exhaustive()` is only relevant for type checking, i.e. they behave the same at run time (throwing an error when no match was found).

I'm not sure why you would even want to use `.run()`?
I'm writing this because I was expecting it to behave like `.otherwise(() => undefined)` but based on my observation that is not the case.

I think the documentation of `.run()` should clarify the distinction (and use case, if any).

If you confirm that I have indeed understood how it works, I'd be happy to supply a PR.

Thanks for the great project! <3

**Comment by gvergnaud** [comment]
Hi! thank you for the kind word

> As far as I understand, the difference between .run() and .exhaustive() is only relevant for type checking, i.e. they behave the same at run time (throwing an error when no match was found).

That's correct.

> I'm not sure why you would even want to use .run()?

It's an escape hatch in case people's types aren't correct and they don't want TS-Pattern to complain about a type error which actually doesn't occur at runtime. I agree `.exhaustive()` is preferable, but it can also be pretty expensive in terms of type checking time, depending on the complexity of the patterns and of the input type. For these 2 reasons, I decided to leave `.run()` as an (unsafe) alternative to `.exhaustive()`.

> I think the documentation of .run() should clarify the distinction (and use case, if any). If you confirm that I have indeed understood how it works, I'd be happy to supply a PR.

Please do, I'd be happy to review your PR :)
