### ISSUE TITLE
P.when parameter is unknown instead of passed type

### ISSUE THREAD

**Issue by alextes** [gvergnaud/ts-pattern#85]
**Describe the bug**
When matching on a value like `number`, a `P.when` has parameter `unknown` instead of `number`. Wrapping in an object like shown in the readme does appear to work.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/lucid-paper-yy5qq9?file=/src/index.ts
![Screenshot 2022-04-06 at 12 04 29](https://user-images.githubusercontent.com/2011351/161951344-c409d793-8e0e-4d38-95c3-826f8c80b79f.png)

**Versions**
- TypeScript version: v4.6.3
- ts-pattern version: v4.0.1
- environment: Node v17

**Comment by gvergnaud** [comment]
Hey,

Yeah I'm aware of this bug, I think it's a limitation of TypeScript inference, I've noticed similar behavior with builtin types from the es5 std library, I was planing to open a bug report about this.

As a workaround you can use `match(...).when(predicate, handler)` instead: [Docs](https://github.com/gvergnaud/ts-pattern#when)
