### ISSUE TITLE
P.infer broadens literals

### ISSUE THREAD

**Issue by marcinplatek** [gvergnaud/ts-pattern#88]
I'm not sure if this is working as intended, but I would prefer if P.infer didn't change literals to their respective broader types, e.g.

```
const ExamplePattern = P.union("a", "b", "c");

type ExampleType =  P.infer<typeof ExamplePattern>
```

Currently, ExampleType would be equal to "string", not "a" | "b" | "c"

**Comment by marcinplatek** [comment]
Works for me, thanks!

Btw, love the package, couldn't use fp-ts without it.

**Comment by marcinplatek** [comment]
@gvergnaud, I've also noticed that
```
P.union([P.number, P.number] as const, undefined)
```
Will infer to `any` without `as const`.

**Comment by gvergnaud** [comment]
Thanks, I think have a fix for those, will release it soon
