### ISSUE TITLE
Wrong type with Pattern#when

### ISSUE THREAD

**Issue by ninesunsabiu** [gvergnaud/ts-pattern#90]
**Describe the bug**
I try to use ts-pattern with [fp-ts](https://github.com/gcanti/fp-ts)
when I use P.when(some_type_guard_function) is has not expected type

**Code Sandbox with a minimal reproduction case**
the ts version of codesandbox editor is not support 4.7 yet

here is some case, I don't know what happen

<img width="725" alt="image" src="https://user-images.githubusercontent.com/19882837/171897774-f78fdca3-344c-4f65-b983-1c6ebf223bf6.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/19882837/171895675-1deac22d-c5ce-48fa-a9b8-79a07fa1f61a.png">

but when I change the guard function signature to `(fa: any) => fa is Some<number>` or `(fa: unknown) => fa is Some<number>`, it will work!!

<img width="731" alt="image" src="https://user-images.githubusercontent.com/19882837/171900204-f251f972-bc33-4012-a75b-e36c86469b01.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/19882837/171900776-5e67b809-03a1-41c3-aa86-e9ae93959e3c.png">

It has same problem when input type is string | number

<img width="811" alt="image" src="https://user-images.githubusercontent.com/19882837/171901805-15f8aa33-490e-47cb-ab0c-5c51d9cbdc6f.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/19882837/171901928-e62b917f-4b5f-43d3-92fc-938e3f38898d.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/19882837/171901979-3d3303d4-780a-4e95-b419-5bc07bba7c25.png">

but Tuple or Object can work

<img width="835" alt="image" src="https://user-images.githubusercontent.com/19882837/171903898-e4aa4f3c-0da6-4868-8b73-3736583c3690.png">

and I known `match().when()` always correct.

**Versions**
- TypeScript version: 4.7.2
- ts-pattern version: 4.0.2
- environment: chrome

**Comment by gvergnaud** [comment]
Hey!
Thanks for the report, do you mind creating a TypeScript playground example demonstrating the issue you are facing so I can investigate later? it seems like you can import ts-pattern and fp-ts in there: [Playground Example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbxAQxgYwBYBo4AUC+cAZlBCHAOQwDOAtGKjAKZQB2FAUB6JLHAFRxk1YmBrFS5CkTC0anDkA)

**Comment by gvergnaud** [comment]
Thanks for the playgrounds. Sorry I didn't have the time to look into it yet, I'll try to find some time this weekend

**Comment by ninesunsabiu** [comment]
never mind. I tried another way to write my code
