### ISSUE TITLE
abstract away type internals and keep exhaustive check

### ISSUE THREAD

**Issue by err0r500** [gvergnaud/ts-pattern#93]
Hi,
I'd like to find a way not to expose types internals while pattern-matching on them (and keep exhaustive check working).

Using constructors do works for pattern-matching but the exhaustive check doesn't detect missing cases.

I don't know if it's a feature request or just I haven't been able to figure out how to do this with `ts-pattern`.

Here's a minimal example : 
```
import { match, P } from "ts-pattern";

type Left<T> = {
  __type: "Left";
  value: T;
};
const left = <T>(v: T) => ({ __type: "Left", value: v} as Either<T, never>);

type Right<T> = {
  __type: "Right";
  value: T;
};
const right = <T>(v: T) =>({__type: "Right",value: v} as Either<never, T>);

type Either<A, B> = Left<A> | Right<B>;
type TestT = Either<"l1" | "l2", string>;

// any commented clause will cause exhaustive check to fail, good !
const works = (x: TestT) =>
  match(x)
    .with({ __type: "Left", value: "l1" }, () => "left l1")
    .with({ __type: "Left", value: "l2" }, () => "left l2")
    .with({ __type: "Right" }, () => "right")
    .exhaustive();

const doesntWork = (x: TestT) =>
  match(x)
    .with(left("l1") as TestT, () => "left l1")
    //.with(left('l2') as TestT, () => "left l2") // this doesn't cause any issue at build time :(
    .with(right(P.select()), (v) => "right :" + v)
    .exhaustive();

// ... but pattern-matching works
console.log(doesntWork(left("l1")));
//console.log(doesntWork(left("l2")))
console.log(doesntWork(right("hello")));
```

Best,
Matthieu

**Comment by gvergnaud** [comment]
Hey,

The only way to make ts-pattern aware of the case that has been handled in a branch is to type your constructor functions more precisely. if your `left()` function returns a `Either<a, b>`, ts-pattern will think it handles every possible values of type `Either<a, b>`, so making  `left()` return a `Left<a>` will fix your issue. 

Unlike most functional programming languages, TypeScript has union types so you don't actually need to return values of type `Either` from constructors and a `Left` will be assignable to a `Either`.

Alternatively, some libraries like [Boxed](https://github.com/swan-io/boxed) choose to expose patterns separately, so you can do things like `Either.patterns.Just(P.select())` ([1](https://swan-io.github.io/boxed/async-data#ts-pattern-interop))
