### ISSUE TITLE
Example with `NaN` isn't working

### ISSUE THREAD

**Issue by johnknoop** [gvergnaud/ts-pattern#98]
According to the readme, you should be able to match on `NaN`, but this doesn't seem to be working.

Steps to reproduce:

```ts
const result = match(NaN)
    .with(NaN, () => 50)
    .otherwise(n => n);
```

Expected result: `50`.
Observed result: `NaN`.

**Comment by gvergnaud** [comment]
Seems like it's working here: https://codesandbox.io/s/charming-turing-gulmwm?file=/src/index.ts:0-132

What version of ts-pattern are you using? `NaN` is supported only since v4. without a playground to reproduce your issue I can't help

**Comment by johnknoop** [comment]
Aha, that explains it. I'm using v3. Thanks.
